/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import Mathlib.Probability.ConditionalExpectation
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.Process.Filtration

/-!
# The strict past of a sequence of random variables

For a sequence of measurable random variables `ξ : ℕ → Ω → β`,
`MeasureTheory.Filtration.naturalPast ξ hξ` is the filtration generated by the strict past:
at time `n` it is the σ-algebra generated by `ξ 0, …, ξ (n - 1)` (trivial at `0`), so that `ξ n`
is measurable at time `n + 1` (`MeasureTheory.Filtration.measurable_naturalPast_succ`). Mathlib's
`MeasureTheory.Filtration.natural` includes the present instead.

For an independent sequence, `ξ n` is independent of its strict past
(`ProbabilityTheory.iIndepFun.indep_comap_naturalPast`), hence the conditional expectation of a
function of `ξ n` given the strict past is its expectation
(`ProbabilityTheory.iIndepFun.condExp_naturalPast_ae_eq`): the centered variables form martingale
differences for this filtration.

For an i.i.d. sequence of law `ν` with values in a countable type, the prefix
`(ξ 0, …, ξ (n - 1))` has law `ν^{⊗ n}` (`ProbabilityTheory.iIndepFun.measure_prefix_mem_eq_pi`).
-/

@[expose] public section

open MeasureTheory

namespace MeasureTheory.Filtration

variable {Ω β : Type*} {mΩ : MeasurableSpace Ω} {mβ : MeasurableSpace β}

/-- The filtration generated by the strict past of a sequence of random variables: at time `n`,
the σ-algebra generated by `ξ 0, …, ξ (n - 1)`. -/
def naturalPast (ξ : ℕ → Ω → β) (hξ : ∀ i, Measurable (ξ i)) : Filtration ℕ mΩ where
  seq n := ⨆ i < n, mβ.comap (ξ i)
  mono' _ _ hnm := biSup_mono fun _ hi ↦ lt_of_lt_of_le hi hnm
  le' _ := iSup₂_le fun i _ ↦ (hξ i).comap_le

/-- Unfolding lemma for `naturalPast`. -/
lemma naturalPast_apply (ξ : ℕ → Ω → β) (hξ : ∀ i, Measurable (ξ i)) (n : ℕ) :
    naturalPast ξ hξ n = ⨆ i < n, mβ.comap (ξ i) := rfl

/-- The variable `ξ i` is measurable with respect to the strict past at time `i + 1`. -/
lemma measurable_naturalPast_succ (ξ : ℕ → Ω → β) (hξ : ∀ i, Measurable (ξ i)) (i : ℕ) :
    Measurable[naturalPast ξ hξ (i + 1)] (ξ i) :=
  (comap_measurable (ξ i)).mono
    (le_iSup₂ (f := fun j (_ : j < i + 1) ↦ mβ.comap (ξ j)) i (Nat.lt_succ_self i)) le_rfl

end MeasureTheory.Filtration

namespace ProbabilityTheory

variable {Ω β : Type*} {mΩ : MeasurableSpace Ω} {mβ : MeasurableSpace β} {μ : Measure Ω}
  {ξ : ℕ → Ω → β}

/-- For an independent sequence, `ξ i` is independent of its strict past. -/
lemma iIndepFun.indep_comap_naturalPast (hξ : ∀ i, Measurable (ξ i)) (hind : iIndepFun ξ μ)
    (i : ℕ) : Indep (mβ.comap (ξ i)) (Filtration.naturalPast ξ hξ i) μ := by
  have h := indep_iSup_of_disjoint (m := fun j ↦ mβ.comap (ξ j)) (fun j ↦ (hξ j).comap_le)
    ((iIndepFun_iff_iIndep _ _ _).1 hind) (S := {i}) (T := Set.Iio i) (by simp)
  simpa [Filtration.naturalPast_apply] using h

/-- For an independent sequence, the conditional expectation of a function of `ξ i` given the
strict past is its expectation. -/
lemma iIndepFun.condExp_naturalPast_ae_eq [IsFiniteMeasure μ] (hξ : ∀ i, Measurable (ξ i))
    (hind : iIndepFun ξ μ) (i : ℕ) {f : β → ℝ} (hf : Measurable f) :
    μ[fun ω ↦ f (ξ i ω) | Filtration.naturalPast ξ hξ i] =ᵐ[μ] fun _ ↦ μ[fun ω ↦ f (ξ i ω)] :=
  condExp_indep_eq (hξ i).comap_le ((Filtration.naturalPast ξ hξ).le i)
    (hf.comp (comap_measurable (ξ i))).stronglyMeasurable (hind.indep_comap_naturalPast hξ i)

/-- For an i.i.d. sequence `ξ` of law `ν`, the prefix `(ξ 0, …, ξ (n - 1))` has law `ν^{⊗ n}`. -/
lemma iIndepFun.measure_prefix_mem_eq_pi [Countable β] [MeasurableSingletonClass β]
    {ν : Measure β} (hind : iIndepFun ξ μ) (hlaw : ∀ k, HasLaw (ξ k) ν μ) (n : ℕ)
    (C : Set (Fin n → β)) :
    μ {ω | (fun k : Fin n ↦ ξ k ω) ∈ C} = Measure.pi (fun _ : Fin n ↦ ν) C := by
  have hind' : iIndepFun (fun k : Fin n ↦ ξ k) μ := hind.precomp Fin.val_injective
  have hmap : μ.map (fun ω (k : Fin n) ↦ ξ k ω) = Measure.pi (fun _ : Fin n ↦ ν) := by
    rw [hind'.map_fun_eq_pi_map (fun k : Fin n ↦ (hlaw k).aemeasurable)]
    simp_rw [(hlaw _).map_eq]
  rw [← hmap, Measure.map_apply₀ (AEMeasurable.of_eval fun k : Fin n ↦ (hlaw k).aemeasurable)
    (Set.to_countable C).measurableSet.nullMeasurableSet]
  rfl

end ProbabilityTheory
