#!/usr/bin/env python3
r"""Generate the comparator challenge files and configs for the headline results.

For each declaration listed in `comparator/targets.txt` this

1. takes the standalone extraction produced by `referee extract` (the project's definitions
   the statement rests on, copied verbatim, with the theorem proof replaced by `sorry`),
2. replaces its `LeanMachineLearning.*` imports by Mathlib imports and inserts the LML
   declarations the statements rest on, copied verbatim from LML in
   `comparator/vendor/LML.lean.part`, so that the import closure bottoms out in Mathlib,
3. writes `comparator/Challenge_<name>.lean` and `comparator/<name>.json`.

Usage (from the repository root, after `lake build`):

    scripts/make-challenges.py [--referee PATH] [--keep-extracted DIR]

The referee binary is looked up in `$REFEREE_BIN`, then `~/.cache/entropy-mdp/referee/*/referee`.
Check the result with `lake build Comparator` (every challenge must compile) and
`scripts/comparator-verify.sh` (comparator itself).
"""
import glob
import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR_IMPORTS = [
    "Mathlib.MeasureTheory.MeasurableSpace.Embedding",
    "Mathlib.Order.Restriction",
    "Mathlib.Probability.HasCondDistrib",
    "Mathlib.Probability.HasLaw",
    "Mathlib.Probability.Kernel.Composition.MeasureCompProd",
    "Mathlib.Probability.Kernel.IonescuTulcea.Maps",
    "Mathlib.Probability.Kernel.IonescuTulcea.Traj",
    "Mathlib.Probability.Process.HittingTime",
]
PERMITTED_AXIOMS = ["propext", "Classical.choice", "Quot.sound"]


DECL_RE = re.compile(r"^(?:@\[[^\]]*\]\s*)?(?:(?:private|protected|noncomputable)\s+)*(?:lemma|theorem)\s+([^\s{(:\[]+)")


def sorried_theorems(text):
    """Fully qualified names of the lemmas/theorems declared in the challenge text (all of
    which referee leaves as `sorry`), following `namespace`/`end` nesting."""
    stack = []
    out = []
    for line in text.split("\n"):
        m = re.match(r"^namespace\s+(\S+)", line)
        if m:
            stack.append(m.group(1))
            continue
        m = re.match(r"^end\s+(\S+)", line)
        if m and stack and stack[-1] == m.group(1):
            stack.pop()
            continue
        m = DECL_RE.match(line)
        if m:
            out.append(".".join(stack + [m.group(1)]))
    return out


def find_referee(arg):
    if arg:
        return arg
    if os.environ.get("REFEREE_BIN"):
        return os.environ["REFEREE_BIN"]
    cands = glob.glob(os.path.expanduser("~/.cache/entropy-mdp/referee/*/referee"))
    if not cands:
        sys.exit("referee binary not found; pass --referee PATH or set REFEREE_BIN")
    return sorted(cands)[-1]


def main():
    args = sys.argv[1:]
    referee = None
    keep = None
    while args:
        a = args.pop(0)
        if a == "--referee":
            referee = args.pop(0)
        elif a == "--keep-extracted":
            keep = args.pop(0)
        else:
            sys.exit(__doc__)
    referee = find_referee(referee)
    targets = [t.strip() for t in open(os.path.join(ROOT, "comparator", "targets.txt")) if t.strip()]
    vendor = open(os.path.join(ROOT, "comparator", "vendor", "LML.lean.part")).read().rstrip("\n")

    work = keep or tempfile.mkdtemp(prefix="entropy-mdp-referee-")
    data = os.path.join(work, "data.json")
    out = os.path.join(work, "out")
    subprocess.run(["lake", "env", referee, "collect", "--root", "Essakine2026Tight", "--data", data],
                   cwd=ROOT, check=True)
    subprocess.run(["lake", "env", referee, "extract", "--root", "Essakine2026Tight", "--data", data,
                    "--output", out], cwd=ROOT, check=True)

    for t in targets:
        src = os.path.join(out, "html-multi", "extracted", f"Essakine2026Tight___{t}.lean")
        lines = open(src).read().split("\n")
        imports = [l for l in lines if l.startswith("import ")]
        body_start = len(imports)
        while body_start < len(lines) and (lines[body_start].startswith("import ") or lines[body_start] == ""):
            body_start += 1
        body = lines[body_start:]
        mathlib_imports = [l[len("import "):] for l in imports if l.startswith("import Mathlib")]
        lml_imports = [l for l in imports if l.startswith("import LeanMachineLearning")]
        other = [l for l in imports if not (l.startswith("import Mathlib") or l.startswith("import LeanMachineLearning"))]
        if other:
            sys.exit(f"{t}: unexpected imports {other}")
        all_imports = []
        for m in VENDOR_IMPORTS + mathlib_imports:
            if m not in all_imports:
                all_imports.append(m)
        text = "\n".join(body)
        text = text.replace(
            "Auto-generated by Referee. -/",
            "Auto-generated by Referee (`scripts/make-challenges.py`), with the LML declarations the\n"
            "statement rests on vendored in below, so that this file is self-contained over Mathlib\n"
            "(its transitive imports resolve to Mathlib and Lean core only). -/")
        # insert the vendored block before the first project section
        idx = text.index("\n-- ═══ ")
        text = text[:idx] + "\n" + vendor + "\n" + text[idx:]
        header = "\n".join(f"import {m}" for m in all_imports) + "\n\n"
        dst = os.path.join(ROOT, "comparator", f"Challenge_{t}.lean")
        open(dst, "w").write(header + text.rstrip("\n") + "\n")
        # Every lemma/theorem in the challenge has its proof replaced by `sorry` (referee does this
        # for the target and for the project lemmas the definitions rest on). Comparator compares
        # the *values* of the theorems in the statement's closure, so each sorry'd lemma must be
        # listed as a target too: comparator then verifies that the solution proves it instead of
        # requiring an identical proof term.
        names = [f"Essakine2026Tight.{t}"] + [n for n in sorried_theorems(text) if n != f"Essakine2026Tight.{t}"]
        cfg = {
            "challenge_module": f"Challenge_{t}",
            "solution_module": "Solution",
            "theorem_names": names,
            "permitted_axioms": PERMITTED_AXIOMS,
        }
        open(os.path.join(ROOT, "comparator", f"{t}.json"), "w").write(json.dumps(cfg, indent=4) + "\n")
        print(f"wrote Challenge_{t}.lean ({len(lml_imports)} LML imports replaced)")


if __name__ == "__main__":
    main()
