import Mathlib.MeasureTheory.MeasurableSpace.Embedding
import Mathlib.Order.Restriction
import Mathlib.Probability.HasCondDistrib
import Mathlib.Probability.HasLaw
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.Probability.Kernel.IonescuTulcea.Maps
import Mathlib.Probability.Kernel.IonescuTulcea.Traj
import Mathlib.Probability.Process.HittingTime
import Mathlib.Probability.Kernel.Basic
import Mathlib.MeasureTheory.Measure.Real
import Mathlib.MeasureTheory.Function.EssSup
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.Nat.Log
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-! # Standalone extraction for `Essakine2026Tight.isEntropicPAC_entropicBPI`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee (`scripts/make-challenges.py`), with the LML declarations the
statement rests on vendored in below, so that this file is self-contained over Mathlib
(its transitive imports resolve to Mathlib and Lean core only). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning
end Learning
namespace Learning.MDP
end Learning.MDP
namespace Learning.MDP.Episodic
end Learning.MDP.Episodic
namespace Learning.MDP.Episodic.EpisodicMDP
end Learning.MDP.Episodic.EpisodicMDP
namespace Learning.MDP.EmpiricalModel
end Learning.MDP.EmpiricalModel
namespace Essakine2026Tight
end Essakine2026Tight

-- ═══ vendored from LML: LeanMachineLearning.ForMathlib.MeasureTheory.MeasurableSpace.Embedding ═══
-- The declarations of https://github.com/LeanMachineLearning/LML that the statement rests on,
-- copied verbatim (Apache 2.0, Authors: Rémy Degenne, Paulo Rauber) so that this file's imports
-- bottom out in Mathlib. Comparator checks each constant is *identical* to the LML package's.
section
open Finset Preorder
namespace MeasurableEquiv

section Fin

variable {X : ℕ → Type*} [∀ n, MeasurableSpace (X n)]

/-- Measurable equivalence between `Π i : Fin (n + 1), X i` and `Π i : Iic n, X i`. -/
def finSuccPiIic (X : ℕ → Type*) [∀ n, MeasurableSpace (X n)] (n : ℕ) :
    (Π i : Fin (n + 1), X i) ≃ᵐ (Π i : Iic n, X i) where
  toFun h i := h ⟨i.1, Nat.lt_succ_of_le (mem_Iic.mp i.2)⟩
  invFun h i := h ⟨i.1, mem_Iic.mpr (Nat.le_of_lt_succ i.2)⟩
  left_inv _ := rfl
  right_inv _ := rfl
  measurable_toFun := .of_eval fun _ ↦ measurable_pi_apply _
  measurable_invFun := .of_eval fun _ ↦ measurable_pi_apply _

end Fin

end MeasurableEquiv
end

-- ═══ vendored from LML: LeanMachineLearning.ForMathlib.Probability.Kernel.IonescuTulcea.Traj ═══
section
open Filter Finset Function MeasurableEquiv MeasurableSpace MeasureTheory Preorder ProbabilityTheory

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω}
  {X : ℕ → Type*} [∀ n, MeasurableSpace (X n)]
  {κ : (n : ℕ) → Kernel (Π i : Iic n, X i) (X (n + 1))} [∀ n, IsMarkovKernel (κ n)]
  {μ₀ : Measure (X 0)} [IsProbabilityMeasure μ₀]

namespace ProbabilityTheory.Kernel

section FinTraj

variable {κ' : (n : ℕ) → Kernel (Π i : Fin n, X i) (X n)} [∀ n, IsMarkovKernel (κ' n)]

/-- Kernels indexed by `Iic n` (as needed for `Kernel.traj`), obtained from kernels indexed by
`Fin n`: the kernel `κ' (n + 1)` on `Π i : Fin (n + 1), X i` is seen as a kernel on
`Π i : Iic n, X i`. -/
noncomputable
def iicOfFin (κ' : (n : ℕ) → Kernel (Π i : Fin n, X i) (X n)) (n : ℕ) :
    Kernel (Π i : Iic n, X i) (X (n + 1)) :=
  (κ' (n + 1)).comap (MeasurableEquiv.finSuccPiIic X n).symm (by fun_prop)

instance (n : ℕ) : IsMarkovKernel (iicOfFin κ' n) := by unfold iicOfFin; infer_instance

/-- Measure on trajectories `Π n, X n` built from kernels `κ' n : Kernel (Π i : Fin n, X i) (X n)`
describing the law of the coordinate `n` given the `n` previous coordinates.
The initial measure is `κ' 0 default`. -/
noncomputable
def trajMeasureFin (κ' : (n : ℕ) → Kernel (Π i : Fin n, X i) (X n)) [∀ n, IsMarkovKernel (κ' n)] :
    Measure (Π n, X n) :=
  trajMeasure (κ' 0 default) (iicOfFin κ')
deriving IsProbabilityMeasure

end FinTraj

end ProbabilityTheory.Kernel
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Algorithm ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The observation of a round. -/
def Round.obs (r : Round 𝓞 𝓐 𝓨) : 𝓞 := r.1
/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1
/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.obs n) := env.isMarkovKernel_obs n
instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) :=
  env.isMarkovKernel_feedback n

/-- Kernel describing the distribution of the round at time `n` given the history before `n`. -/
noncomputable
def stepKernel (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    Kernel (Hist 𝓞 𝓐 𝓨 n) (Round 𝓞 𝓐 𝓨) :=
  env.obs n ⊗ₖ (alg.policy n ⊗ₖ env.feedback n)
deriving IsMarkovKernel

section IsAlgEnvSeq

variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StationaryEnv ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- An oblivious environment without observations, in which the distribution of the next feedback
depends only on the last action, but in a possibly time-dependent manner. -/
@[simps]
noncomputable
def obliviousEnv (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment Unit 𝓐 𝓨 where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n := (ν n).prodMkLeft _

/-- A stationary environment without observations, in which the distribution of the next feedback
depends only on the last action. -/
noncomputable
def stationaryEnv (ν : Kernel 𝓐 𝓨) [IsMarkovKernel ν] : Environment Unit 𝓐 𝓨 :=
  obliviousEnv fun _ ↦ ν

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Deterministic ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- A deterministic algorithm, which chooses the action given by the function `nextA`.
The initial action is `fun o ↦ nextA 0 (default, o)`. -/
@[simps]
noncomputable
def detAlgorithm (nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐)
    (h_next : ∀ n, Measurable (nextA n)) :
    Algorithm 𝓞 𝓐 𝓨 where
  policy n := Kernel.deterministic (nextA n) (h_next n)

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.IonescuTulceaSpace ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- Measure on the sequence of rounds generated by the algorithm/environment. -/
noncomputable
def trajMeasure (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    Measure (ℕ → Round 𝓞 𝓐 𝓨) :=
  Kernel.trajMeasureFin (stepKernel alg env)
deriving IsProbabilityMeasure

namespace IT

/-- `obs n` is the observation at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def obs (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓞 := (h n).obs

/-- `action n` is the action pulled at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def action (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓐 := (h n).action

/-- `feedback n` is the feedback at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def feedback (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓨 := (h n).feedback

end IT

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StoppedHistory ═══
section
open MeasureTheory ProbabilityTheory
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}
  {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
  {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)}
  {τ : Ω → WithTop ℕ} {ω : Ω} {n M : ℕ}

/-- The history of the first `n` rounds, as a history of variable length in the sigma type
`Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n`. -/
def sigmaHistory (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) :
    Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  ⟨n, history O X Y n ω⟩

section StoppedHistMeasure

/-- The law of the history stopped by the stopping rule `S`, for the algorithm `alg` in the
environment `env`: the law of the stopped history on the canonical space `trajMeasure alg env`.
This is the law of the stopped history for any algorithm-environment sequence
(`IsAlgEnvSeq.hasLaw_stoppedValue_sigmaHistory`). -/
noncomputable def stoppedHistMeasure (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)) :
    Measure (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n) :=
  (trajMeasure alg env).map
    (stoppedValue (sigmaHistory IT.obs IT.action IT.feedback)
      (hittingAfter (sigmaHistory IT.obs IT.action IT.feedback) S 0))
deriving IsProbabilityMeasure

end StoppedHistMeasure

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.IdentificationAlg ═══
section
open MeasureTheory ProbabilityTheory
open scoped ENat
namespace Learning

variable {𝓞 𝓐 𝓨 𝓓 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {m𝓓 : MeasurableSpace 𝓓} {mΩ : MeasurableSpace Ω}
  {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}

/-- An identification algorithm with outputs in `𝓓`: a sampling rule `alg`, a stopping rule
`stopSet` (the algorithm stops after `n` rounds if the history of these rounds belongs to
`stopSet`) and an output rule `output`, a Markov kernel giving the distribution of the output
given the history of the rounds played. -/
structure IdentAlg (𝓞 𝓐 𝓨 𝓓 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐]
    [MeasurableSpace 𝓨] [MeasurableSpace 𝓓] where
  /-- The sampling rule. -/
  alg : Algorithm 𝓞 𝓐 𝓨
  /-- The stopping rule: the algorithm stops after `n` rounds if the history of these rounds
  belongs to `stopSet`. -/
  stopSet : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)
  /-- The stopping rule is measurable. -/
  measurableSet_stopSet : MeasurableSet stopSet
  /-- The output rule: distribution of the output given the history of the rounds played. -/
  output : Kernel (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n) 𝓓
  /-- The output rule is a Markov kernel. -/
  [isMarkovKernel_output : IsMarkovKernel output]

namespace IdentAlg

variable {A : IdentAlg 𝓞 𝓐 𝓨 𝓓} {env : Environment 𝓞 𝓐 𝓨} {out : Ω → 𝓓} {P : Measure Ω}

instance : IsMarkovKernel A.output := A.isMarkovKernel_output

/-- The stopping time of `A` on the observation, action and feedback processes `O`, `X`, `Y`: the
number of rounds played, that is the first `n` such that the history of the first `n` rounds
belongs to the stopping rule `A.stopSet` (`⊤` if there is none). -/
noncomputable def stoppingTime (A : IdentAlg 𝓞 𝓐 𝓨 𝓓)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    Ω → ℕ∞ :=
  hittingAfter (sigmaHistory O X Y) A.stopSet 0

/-- The history of the rounds played by an identification algorithm `A`, as a history of variable
length: the history stopped at `A.stoppingTime O X Y`
(the history of an arbitrary number of rounds if `A` never stops). -/
noncomputable def stoppedHist (A : IdentAlg 𝓞 𝓐 𝓨 𝓓)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    Ω → Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  stoppedValue (sigmaHistory O X Y) (A.stoppingTime O X Y)

/-- `(O, X, Y, out)` is a *run* of the identification algorithm `A` in the environment `env` on
the probability space `(Ω, P)`: the observation, action and feedback processes `O`, `X`, `Y` form
an algorithm-environment sequence for the sampling rule `A.alg` and `env`, and the output `out` has
conditional law `A.output` given the history at the stopping time. -/
structure IsRun (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Environment 𝓞 𝓐 𝓨)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (out : Ω → 𝓓)
    (P : Measure Ω := by volume_tac) [IsFiniteMeasure P] : Prop where
  /-- The actions and feedbacks are generated by the sampling rule in the environment. -/
  isAlgEnvSeq : IsAlgEnvSeq O X Y A.alg env P
  /-- The output is drawn from the output rule applied to the history at the stopping time. -/
  hasCondDistrib_output : HasCondDistrib out (A.stoppedHist O X Y) A.output P

/-- The law of the output of an identification algorithm in an environment. -/
noncomputable def outputMeasure (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Environment 𝓞 𝓐 𝓨) : Measure 𝓓 :=
  A.output ∘ₘ stoppedHistMeasure A.alg env A.stopSet
deriving IsProbabilityMeasure

section IsPAC

/-- `A` is *PAC at level `δ`* for the family of environments `env : Θ → Environment 𝓞 𝓐 𝓨` and
the predicate `bad : Θ → 𝓓 → Prop` if, for every `θ`, the output of `A` in `env θ` is
`bad θ` with probability at most `δ`.
See `IsPAC.measureReal_not_good_of_isRun` for the corresponding statement about any run of `A`. -/
def IsPAC {Θ : Type*} (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Θ → Environment 𝓞 𝓐 𝓨)
    (bad : Θ → 𝓓 → Prop) (δ : ℝ) : Prop :=
  ∀ θ, (A.outputMeasure (env θ)).real {d | bad θ d} ≤ δ

end IsPAC

end IdentAlg

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.ForMathlib.MeasureTheory.Order.MeasurableArg ═══
section
open Finset

variable {ι α : Type*} [LinearOrder α] [Fintype ι] [Nonempty ι] (f : ι → α)

namespace Function

/-- The maximum value of a tuple. -/
abbrev max : α := univ.sup' univ_nonempty f

/-- The minimum value of a tuple. -/
abbrev min : α := univ.inf' univ_nonempty f

end Function

lemma exists_argmax : ∃ i, f i = f.max := sorry

lemma exists_argmin : ∃ i, f i = f.min := sorry

/-- The index of the maximum value of a tuple. -/
noncomputable def argmax := (exists_argmax f).choose

/-- The index of the minimum value of a tuple. -/
noncomputable def argmin := (exists_argmin f).choose

end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Basic ═══
section
open MeasureTheory ProbabilityTheory Learning

/-- Markov decision process with state space `𝓢`, action space `𝓐`, and reward space `𝓡`, described
by a transition kernel `P : Kernel (𝓢 × 𝓐) 𝓢` and a reward kernel `R : Kernel (𝓢 × 𝓐) 𝓡`.
See `MDP.env` for the environment associated with the MDP. -/
structure MDP (𝓢 𝓐 𝓡 : Type*) [MeasurableSpace 𝓢] [MeasurableSpace 𝓐] [MeasurableSpace 𝓡] where
  /-- The transition kernel: the law of the next state given the current state and action. -/
  P : Kernel (𝓢 × 𝓐) 𝓢
  /-- The transition kernel is a Markov kernel. -/
  [hP : IsMarkovKernel P]
  /-- The reward kernel: the law of the reward given the current state and action. -/
  R : Kernel (𝓢 × 𝓐) 𝓡
  /-- The reward kernel is a Markov kernel. -/
  [hR : IsMarkovKernel R]

namespace Learning.MDP
variable {𝓢 𝓐 𝓡 : Type*} {m𝓢 : MeasurableSpace 𝓢} {m𝓐 : MeasurableSpace 𝓐} {m𝓡 : MeasurableSpace 𝓡}

instance (M : MDP 𝓢 𝓐 𝓡) : IsMarkovKernel M.R := M.hR

/-- The state and the action of the last round of a history of `n + 1` rounds. -/
def lastObsAction (n : ℕ) (h : Hist 𝓢 𝓐 𝓡 (n + 1)) : 𝓢 × 𝓐 :=
  ((h (Fin.last n)).obs, (h (Fin.last n)).action)

lemma measurable_lastObsAction (n : ℕ) :
    Measurable (lastObsAction (𝓢 := 𝓢) (𝓐 := 𝓐) (𝓡 := 𝓡) n) := sorry

/-- The current state and the action of a round, from the history, the observation and the
action. -/
def obsAction (n : ℕ) (p : (Hist 𝓢 𝓐 𝓡 n × 𝓢) × 𝓐) : 𝓢 × 𝓐 := (p.1.2, p.2)

lemma measurable_obsAction (n : ℕ) : Measurable (obsAction (𝓢 := 𝓢) (𝓐 := 𝓐) (𝓡 := 𝓡) n) := sorry

/-- The observation kernel of the environment of `M` with initial state distribution `μ₀`: the
initial state is drawn from `μ₀`, and the state of round `n + 1` from `M.P` applied to the state
and action of round `n`. -/
noncomputable def envObs (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) (n : ℕ) : Kernel (Hist 𝓢 𝓐 𝓡 n) 𝓢 :=
  Nat.rec (motive := fun n ↦ Kernel (Hist 𝓢 𝓐 𝓡 n) 𝓢) (Kernel.const _ μ₀)
    (fun n _ ↦ M.P.comap (lastObsAction n) (measurable_lastObsAction n)) n

lemma isMarkovKernel_envObs (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) [IsProbabilityMeasure μ₀] (n : ℕ) :
    IsMarkovKernel (envObs M μ₀ n) := sorry

instance (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) [IsProbabilityMeasure μ₀] (n : ℕ) :
    IsMarkovKernel (envObs M μ₀ n) :=
  isMarkovKernel_envObs M μ₀ n

/-- The environment of the MDP `M` with initial state distribution `μ₀`: the observation of a
round is the current state (drawn from `μ₀` at the first round, then from `M.P (s, a)` for the
state `s` and action `a` of the previous round), and the feedback is the reward, drawn from
`M.R (s, a)`. -/
protected noncomputable def env (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) [IsProbabilityMeasure μ₀] :
    Environment 𝓢 𝓐 𝓡 where
  obs := envObs M μ₀
  feedback n := M.R.comap (obsAction n) (measurable_obsAction n)

lemma measurable_policyAlg_next {π : 𝓢 → 𝓐} (hπ : Measurable π) (n : ℕ) :
    Measurable fun p : Hist 𝓢 𝓐 𝓡 n × 𝓢 ↦ π p.2 := sorry

/-- The stationary deterministic policy `π` as an algorithm: it plays `π s` in the current
state `s`. -/
noncomputable def policyAlg (π : 𝓢 → 𝓐) (hπ : Measurable π) : Algorithm 𝓢 𝓐 𝓡 :=
  detAlgorithm (fun _ p ↦ π p.2) (measurable_policyAlg_next hπ)

/-- The law of the trajectory of the policy `π` started at the state `s`: `E^π_s`. -/
noncomputable def policyMeasure (M : MDP 𝓢 𝓐 𝓡) (π : 𝓢 → 𝓐) (hπ : Measurable π) (s : 𝓢) :
    Measure (ℕ → Round 𝓢 𝓐 𝓡) :=
  trajMeasure (policyAlg π hπ) (M.env (Measure.dirac s))

variable [NormedAddCommGroup 𝓡] [NormedSpace ℝ 𝓡]
end Learning.MDP
end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Vec ═══
section
open MeasureTheory ProbabilityTheory Finset
namespace Learning.MDP
variable {S : Type*} [Fintype S]

/-- The expectation `∑ s, p s * f s` of `f : S → ℝ` under the probability vector `p` (`(p f)` in
the papers). -/
def vecExp (p f : S → ℝ) : ℝ := ∑ s, p s * f s

/-- The variance `Var_p(f) = ∑ p_s f_s² - (∑ p_s f_s)²` of `f` under the probability vector
`p`. -/
def vecVar (p f : S → ℝ) : ℝ := ∑ s, p s * f s ^ 2 - (∑ s, p s * f s) ^ 2

end Learning.MDP
end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Episodic ═══
section
open MeasureTheory ProbabilityTheory Finset Learning Learning.MDP
namespace Learning.MDP.Episodic
variable {S A : Type*} [Fintype S] [Fintype A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A] [MeasurableSingletonClass A] {H : ℕ}

/-- A finite-horizon MDP with horizon `H`: the transition kernels `trans h : Kernel (S × A) S`
and the reward kernels `reward h : Kernel (S × A) ℝ` at each step `h : Fin H`. -/
structure EpisodicMDP (S A : Type*) [MeasurableSpace S] [MeasurableSpace A] (H : ℕ) where
  /-- The transition kernel at step `h`: the law of the next state. -/
  trans : Fin H → Kernel (S × A) S
  /-- The transition kernels are Markov kernels. -/
  [isMarkovKernel_trans : ∀ h, IsMarkovKernel (trans h)]
  /-- The reward kernel at step `h`: the law of the reward. -/
  reward : Fin H → Kernel (S × A) ℝ
  /-- The reward kernels are Markov kernels. -/
  [isMarkovKernel_reward : ∀ h, IsMarkovKernel (reward h)]

/-- A deterministic non-stationary policy. -/
abbrev Policy (S A : Type*) (H : ℕ) := Fin H → S → A

/-- The state sequence `s_1, …, s_{H+1}` of an episode. -/
abbrev Traj (S : Type*) (H : ℕ) := Fin (H + 1) → S

/-- The layered state space: a state together with a step index. -/
abbrev LayerState (S : Type*) (H : ℕ) := S × Fin (H + 1)

omit [Fintype S] [Fintype A] [MeasurableSingletonClass S] [MeasurableSingletonClass A] in
/-- The first step, `0 : Fin (H + 1)` (written without the numeral, which would introduce a
nested `NeZero` proof in every definition using it). -/
def startStep (H : ℕ) : Fin (H + 1) := ⟨0, Nat.zero_lt_succ H⟩

namespace EpisodicMDP

omit [Fintype S] [Fintype A] [MeasurableSingletonClass S] [MeasurableSingletonClass A] in
/-- The rewards of `M` are the deterministic reward function `r`: the reward of `(s, a)` at step
`h` is `r h s a` almost surely. -/
def HasRewardFn (M : EpisodicMDP S A H) (r : Fin H → S → A → ℝ) : Prop :=
  ∀ h s a, M.reward h (s, a) = Measure.dirac (r h s a)

end EpisodicMDP

/-- The transition function of the layered MDP: from `(s, h)` with action `a`, the next layered
state is `(s', h + 1)` with `s' ∼ M.trans h (s, a)` if `h < H`, and `(s, h)` is absorbing at the
terminal layer. -/
noncomputable def layerTransFun (M : EpisodicMDP S A H) (p : LayerState S H × A) :
    Measure (LayerState S H) :=
  if hh : (p.1.2 : ℕ) < H then
    (M.trans ⟨p.1.2, hh⟩ (p.1.1, p.2)).map fun s' ↦ (s', ⟨p.1.2 + 1, Nat.succ_lt_succ hh⟩)
  else Measure.dirac p.1

omit [Fintype S] [Fintype A] in
lemma measurable_layerTransFun [Finite S] [Finite A] (M : EpisodicMDP S A H) :
    Measurable (layerTransFun M) := sorry

/-- The transition kernel of the layered MDP. -/
noncomputable def layerTrans (M : EpisodicMDP S A H) :
    Kernel (LayerState S H × A) (LayerState S H) :=
  ⟨layerTransFun M, measurable_layerTransFun M⟩

lemma isProbabilityMeasure_layerTrans (M : EpisodicMDP S A H) (p : LayerState S H × A) :
    IsProbabilityMeasure (layerTrans M p) := sorry

instance (M : EpisodicMDP S A H) : IsMarkovKernel (layerTrans M) :=
  ⟨isProbabilityMeasure_layerTrans M⟩

/-- The reward function of the layered MDP: `M.reward h (s, a)` at `(s, h)` with `h < H`, and the
reward `0` at the terminal layer. -/
noncomputable def layerRewardFun (M : EpisodicMDP S A H) (p : LayerState S H × A) : Measure ℝ :=
  if hh : (p.1.2 : ℕ) < H then M.reward ⟨p.1.2, hh⟩ (p.1.1, p.2) else Measure.dirac 0

omit [Fintype S] [Fintype A] in
lemma measurable_layerRewardFun [Finite S] [Finite A] (M : EpisodicMDP S A H) :
    Measurable (layerRewardFun M) := sorry

/-- The reward kernel of the layered MDP. -/
noncomputable def layerReward (M : EpisodicMDP S A H) : Kernel (LayerState S H × A) ℝ :=
  ⟨layerRewardFun M, measurable_layerRewardFun M⟩

lemma isProbabilityMeasure_layerReward (M : EpisodicMDP S A H) (p : LayerState S H × A) :
    IsProbabilityMeasure (layerReward M p) := sorry

instance (M : EpisodicMDP S A H) : IsMarkovKernel (layerReward M) :=
  ⟨isProbabilityMeasure_layerReward M⟩

/-- The stationary MDP on the layered state space which embeds the finite-horizon MDP `M`. -/
noncomputable def layerMDP (M : EpisodicMDP S A H) : MDP (LayerState S H) A ℝ where
  P := layerTrans M
  R := layerReward M

variable [Nonempty A]

omit [Fintype S] [Fintype A] [MeasurableSingletonClass S] [MeasurableSingletonClass A] in
/-- A policy of the finite-horizon MDP as a stationary policy of the layered MDP (arbitrary at
the terminal layer). -/
noncomputable def Policy.layer (π : Policy S A H) (p : LayerState S H) : A :=
  if hh : (p.2 : ℕ) < H then π ⟨p.2, hh⟩ p.1 else Classical.arbitrary A

omit [Fintype S] [Fintype A] [MeasurableSingletonClass A] in
lemma Policy.measurable_layer [Finite S] (π : Policy S A H) : Measurable π.layer := sorry

/-- The law of the trajectory of the layered MDP under the policy `π` started at `p₀`: the law
of `(S_i, A_i, R_i)_{i ≥ h}` from the state `s` at step `h` for `p₀ = (s, h)`. -/
noncomputable def stepLaw (M : EpisodicMDP S A H) (π : Policy S A H) (p₀ : LayerState S H) :
    Measure (ℕ → Round (LayerState S H) A ℝ) :=
  (layerMDP M).policyMeasure π.layer π.measurable_layer p₀

omit [Fintype S] [Fintype A] [MeasurableSingletonClass S] [MeasurableSingletonClass A]
  [Nonempty A] in
/-- The return `∑_{i < H} R_i` of a trajectory of the layered MDP (the rewards after the terminal
layer are `0`, so this is the return of the episode from any starting step). -/
def episodeReturn (H : ℕ) (traj : ℕ → Round (LayerState S H) A ℝ) : ℝ :=
  ∑ k ∈ range H, IT.feedback k traj

omit [Fintype S] [Fintype A] [MeasurableSingletonClass S] [MeasurableSingletonClass A]
  [Nonempty A] in
/-- The states `s_1, …, s_{H+1}` of a trajectory of the layered MDP. -/
def episodeStates (H : ℕ) (traj : ℕ → Round (LayerState S H) A ℝ) : Traj S H :=
  fun h ↦ (IT.obs h traj).1

variable (M : EpisodicMDP S A H)

/-- The law of the state sequence of the episode played with the policy `π` from `s₁`. -/
noncomputable def statesLaw (s₁ : S) (π : Policy S A H) : Measure (Traj S H) :=
  (stepLaw M π (s₁, startStep H)).map (episodeStates H)

lemma measurable_statesLaw (s₁ : S) : Measurable (statesLaw M s₁) := sorry

/-- The kernel from policies to the law of the state sequence of the episode played with the
policy from `s₁`. -/
noncomputable def statesKernel (s₁ : S) : Kernel (Policy S A H) (Traj S H) :=
  ⟨statesLaw M s₁, measurable_statesLaw M s₁⟩

lemma isProbabilityMeasure_statesKernel (s₁ : S) (π : Policy S A H) :
    IsProbabilityMeasure (statesKernel M s₁ π) := sorry

instance (s₁ : S) : IsMarkovKernel (statesKernel M s₁) :=
  ⟨isProbabilityMeasure_statesKernel M s₁⟩

/-- The episodic environment with the fixed initial state `s₁` in which the learner observes the
states of the episode only (the rewards being known): at each round, the learner plays a policy
and observes the states. -/
noncomputable def statesEnv (s₁ : S) : Environment Unit (Policy S A H) (Traj S H) :=
  stationaryEnv (statesKernel M s₁)

omit [Fintype S] [Fintype A] [MeasurableSingletonClass S] [MeasurableSingletonClass A]
  [Nonempty A] in
/-- A best-policy identification algorithm: an identification algorithm playing a policy at each
episode, observing the states, and outputting a policy. -/
abbrev BPIAlg (S A : Type*) [MeasurableSpace S] [MeasurableSpace A] (H : ℕ) :=
  IdentAlg Unit (Policy S A H) (Traj S H) (Policy S A H)

end Learning.MDP.Episodic
end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Entropic ═══
section
open MeasureTheory ProbabilityTheory Finset Learning Learning.MDP
namespace Learning.MDP.Episodic
variable {S A : Type*} [Fintype S] [Fintype A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A] [MeasurableSingletonClass A] [Nonempty A] {H : ℕ}

/-- The exponential value `Z^π_h(s) = E[exp(β R_h) | S_h = s]`. -/
noncomputable def expValue (M : EpisodicMDP S A H) (β : ℝ) (π : Policy S A H) (h : Fin (H + 1))
    (s : S) : ℝ :=
  ∫ traj, Real.exp (β * episodeReturn H traj) ∂(stepLaw M π (s, h))

/-- The entropic value `V^π_h(s) = β⁻¹ log E[exp(β R_h) | S_h = s]`. -/
noncomputable def entropicValue (M : EpisodicMDP S A H) (β : ℝ) (π : Policy S A H)
    (h : Fin (H + 1)) (s : S) : ℝ :=
  β⁻¹ * Real.log (expValue M β π h s)

/-- The optimal entropic value `V*_h(s) = ⨆ π, V^π_h(s)`. -/
noncomputable def optEntropicValue (M : EpisodicMDP S A H) (β : ℝ) (h : Fin (H + 1)) (s : S) :
    ℝ :=
  ⨆ π : Policy S A H, entropicValue M β π h s

/-- `𝒜` is `(ε, δ)`-PAC for best-policy identification under the entropic risk measure with
parameter `β`, for the known reward function `r`, from the initial state `s₁`: for every MDP
with reward function `r`, the output `π̂` of `𝒜` in its states-only environment satisfies
`V*_1(s₁) - V^π̂_1(s₁) > ε` with probability at most `δ`. -/
def IsEntropicPAC (𝒜 : BPIAlg S A H) (r : Fin H → S → A → ℝ) (β ε δ : ℝ) (s₁ : S) : Prop :=
  𝒜.IsPAC (fun M : {M : EpisodicMDP S A H // M.HasRewardFn r} ↦ statesEnv M.1 s₁)
    (fun M π ↦
      ε < optEntropicValue M.1 β (startStep H) s₁ - entropicValue M.1 β π (startStep H) s₁) δ

end Learning.MDP.Episodic
end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Empirical ═══
section
open MeasureTheory ProbabilityTheory Finset Learning Learning.MDP Learning.MDP.Episodic
namespace Learning.MDP

/-- The empirical model of a tabular MDP: visit counts, sums of rewards and transition counts of
the state-action pairs. -/
abbrev EmpiricalModel (S A : Type*) := (S × A → ℕ) × (S × A → ℝ) × (S × A → S → ℕ)

namespace EmpiricalModel
variable {S A : Type*} [DecidableEq S] [DecidableEq A]

/-- The empirical model of the single transition `(s, a, r, s')`. -/
def single (s : S) (a : A) (r : ℝ) (s' : S) : EmpiricalModel S A :=
  (fun p ↦ if (s, a) = p then 1 else 0, fun p ↦ if (s, a) = p then r else 0,
    fun p t ↦ if (s, a) = p ∧ s' = t then 1 else 0)

/-- The visit count `N(s, a)`. -/
def count (m : EmpiricalModel S A) (p : S × A) : ℕ := m.1 p

/-- The empirical transition probabilities `P̂(· | s, a)` (`0` for unvisited pairs). -/
noncomputable def empTrans (m : EmpiricalModel S A) (p : S × A) : S → ℝ :=
  fun s' ↦ m.2.2 p s' / m.1 p

variable {H : ℕ}

/-- The empirical model of the transition at step `h` of the episode with policy `π`, states `τ`
and rewards `r`. -/
def ofEpisodeAt (π : Policy S A H) (τ : Traj S H) (r : Fin H → ℝ) (h : Fin H) :
    EmpiricalModel S A :=
  single (τ h.castSucc) (π h (τ h.castSucc)) (r h) (τ h.succ)

end EmpiricalModel
end Learning.MDP
end

-- ═══ EV2026.Rates ═══
section
namespace Essakine2026Tight

/-- The exploration rate `α(n, δ) = log(3 S A H / δ) + S log(8 e (n + 1))`. -/
noncomputable def alphaKL (S A H : ℕ) (δ : ℝ) (n : ℕ) : ℝ :=
  Real.log ((3 * S * A * H : ℕ) / δ) + S * Real.log ((8 : ℕ) * Real.exp 1 * (n + 1 : ℕ))

/-- The exploration rate `α*(n, δ) = log(3 S A H / δ) + log(8 e (n + 1))`. -/
noncomputable def alphaStar (S A H : ℕ) (δ : ℝ) (n : ℕ) : ℝ :=
  Real.log ((3 * S * A * H : ℕ) / δ) + Real.log ((8 : ℕ) * Real.exp 1 * (n + 1 : ℕ))

end Essakine2026Tight
end

-- ═══ EV2026.Algorithm ═══
section
open MeasureTheory ProbabilityTheory Finset Learning Learning.MDP.Episodic Learning.MDP
namespace Essakine2026Tight
section Helpers
variable {S : Type*} [Fintype S]

lemma sub_one_sub_lt {H k : ℕ} (hk : k < H) : H - 1 - k < H := sorry

/-- The `0`-indexed step with `k` steps after it. -/
def stepOf (H k : ℕ) (hk : k < H) : Fin H := ⟨H - 1 - k, sub_one_sub_lt hk⟩

/-- The bonus `b_h^t(s, a)` of a pair visited `n` times with empirical transitions `phat`, from
the next-step optimistic and pessimistic values `Zt`, `Zl`, with `k` steps after `h`, for `nS`
states, `nA` actions and horizon `H`:
`2 √2 √(Var_p̂(Z̃) α*(n)/n) + 5 e^{β k} α(n)/n + 4 H e^{β k} α(n)/n` for `β > 0` (with `Z̲` and
`1 - e^{β k}` for `β < 0`). The third term carries the KL rate `α`, as in the statement of the
paper's Lemma 7 (its bonus (bonus positive) has `α*` there, which does not suffice for Lemma 11;
blueprint, chapter "Analysis for β > 0", `rem:pos_constants_bonus`). -/
noncomputable def bonus (nS nA H : ℕ) (β δ : ℝ) (k n : ℕ) (phat Zt Zl : S → ℝ) : ℝ :=
  let αn := alphaKL nS nA H δ n / n
  let αs := alphaStar nS nA H δ n / n
  if 0 < β then
    (2 : ℕ) * √(2 : ℕ) * √(vecVar phat Zt * αs) + (5 : ℕ) * Real.exp (β * k) * αn
      + (4 * H : ℕ) * Real.exp (β * k) * αn
  else
    (2 : ℕ) * √(2 : ℕ) * √(vecVar phat Zl * αs) + (5 : ℕ) * (1 - Real.exp (β * k)) * αn
      + (4 * H : ℕ) * (1 - Real.exp (β * k)) * αn

/-- The optimistic and pessimistic backups `(Ũ, U̲)(s, a)` of a pair with reward `r`, visited `n`
times with empirical transitions `phat`, from the next-step values `Zt`, `Zl`, with `k` steps
after the current step, clipped at `e^{β (k + 1)}` and `1`; a pair never visited gets the trivial
bounds. -/
noncomputable def stepU (nS nA H : ℕ) (β δ : ℝ) (k n : ℕ) (r : ℝ) (phat Zt Zl : S → ℝ) :
    ℝ × ℝ :=
  let b := bonus nS nA H β δ k n phat Zt Zl
  let w := (1 / H : ℝ) * vecExp phat (Zt - Zl)
  let up := if 0 < β then Real.exp (β * (k + 1)) else 1
  let low := if 0 < β then 1 else Real.exp (β * (k + 1))
  if n = 0 then (up, low) else
    (min up (Real.exp (β * r) * (vecExp phat Zt + b + w)),
      max low (Real.exp (β * r) * (vecExp phat Zl - b - w)))

end Helpers
section Algorithm
variable {S A : Type*} [Fintype S] [Fintype A] [DecidableEq S] [DecidableEq A] [Nonempty A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A] [MeasurableSingletonClass A] {H : ℕ}

omit [Nonempty A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A]
  [MeasurableSingletonClass A] in
/-- The empirical model of the step `h` of a history of episodes (states only, rewards `0`). -/
def stepModel {t : ℕ} (hist : Hist Unit (Policy S A H) (Traj S H) t) (h : Fin H) :
    EmpiricalModel S A :=
  ∑ i, EmpiricalModel.ofEpisodeAt (hist i).action (hist i).feedback 0 h

omit [Nonempty A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A]
  [MeasurableSingletonClass A] in
/-- The number of episodes of the history `hist` in which `(s, a)` was visited at step `h`
(`n_h^t(s, a)`). -/
def visitCount {t : ℕ} (hist : Hist Unit (Policy S A H) (Traj S H) t) (h : Fin H) (s : S)
    (a : A) : ℕ :=
  (stepModel hist h).count (s, a)

omit [Nonempty A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A]
  [MeasurableSingletonClass A] in
/-- The empirical transition probabilities `p̂_h^t(· | s, a)` (uniform if `(s, a)` was never
visited at step `h`). -/
noncomputable def empTrans {t : ℕ} (hist : Hist Unit (Policy S A H) (Traj S H) t) (h : Fin H)
    (s : S) (a : A) : S → ℝ :=
  if visitCount hist h s a = 0 then fun _ ↦ (Fintype.card S : ℝ)⁻¹
  else (stepModel hist h).empTrans (s, a)

/-- One backward step of the optimistic planning: the values `(Z̃, Z̲)` at the step with `k`
steps after it, from the values `prev` at the next step (`stepU` for every pair, then the max
(`β > 0`) or the min (`β < 0`) over the actions); the identity if `k ≥ H`. -/
noncomputable def optZStep (r : Fin H → S → A → ℝ) (β δ : ℝ) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) (k : ℕ) (prev : (S → ℝ) × (S → ℝ)) :
    (S → ℝ) × (S → ℝ) :=
  if hk : k < H then
    let h := stepOf H k hk
    let U := fun s a ↦ stepU (Fintype.card S) (Fintype.card A) H β δ k (visitCount hist h s a)
      (r h s a) (empTrans hist h s a) prev.1 prev.2
    (fun s ↦ if 0 < β then (fun a ↦ (U s a).1).max else (fun a ↦ (U s a).1).min,
      fun s ↦ if 0 < β then (fun a ↦ (U s a).2).max else (fun a ↦ (U s a).2).min)
  else prev

/-- The optimistic and pessimistic exponential values `(Z̃, Z̲)` at the step `H - j` computed
from the history `hist` (backward recursion; `j = 0` is the terminal step, with values `1`). -/
noncomputable def optZ (r : Fin H → S → A → ℝ) (β δ : ℝ) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) (j : ℕ) : (S → ℝ) × (S → ℝ) :=
  Nat.rec (motive := fun _ ↦ (S → ℝ) × (S → ℝ)) (fun _ ↦ 1, fun _ ↦ 1) (optZStep r β δ hist) j

/-- The backups `(Ũ, U̲)(s, a)` at the step `h` computed from the history `hist`. -/
noncomputable def stepUAt (r : Fin H → S → A → ℝ) (β δ : ℝ) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) (h : Fin H) (s : S) (a : A) : ℝ × ℝ :=
  let prev := optZ r β δ hist (H - 1 - h)
  stepU (Fintype.card S) (Fintype.card A) H β δ (H - 1 - h) (visitCount hist h s a) (r h s a)
    (empTrans hist h s a) prev.1 prev.2

/-- The greedy policy `π^{t+1}` computed from the history `hist`: `argmax_a Ũ(s, a)` if `β > 0`,
`argmin_a U̲(s, a)` if `β < 0`. -/
noncomputable def greedy (r : Fin H → S → A → ℝ) (β δ : ℝ) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) : Policy S A H :=
  fun h s ↦ if 0 < β then argmax fun a ↦ (stepUAt r β δ hist h s a).1
    else argmin fun a ↦ (stepUAt r β δ hist h s a).2

/-- One backward step of the certificate: `π^{t+1} G` at the step with `k` steps after it, from
the certificate `prev` at the next step; the identity if `k ≥ H`. -/
noncomputable def certStep (r : Fin H → S → A → ℝ) (β δ : ℝ) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) (k : ℕ) (prev : S → ℝ) : S → ℝ :=
  fun s ↦
    if hk : k < H then
      let h := stepOf H k hk
      let a := greedy r β δ hist h s
      let n := visitCount hist h s a
      let Z := optZ r β δ hist k
      let b := bonus (Fintype.card S) (Fintype.card A) H β δ k n (empTrans hist h s a) Z.1 Z.2
      let clip := if 0 < β then Real.exp (β * (k + 1)) else 1
      if n = 0 then clip else
        min clip (Real.exp (β * r h s a) *
          ((3 : ℕ) * b + (1 + (3 : ℕ) / H) * vecExp (empTrans hist h s a) prev))
    else prev s

/-- The certificate `π^{t+1} G` at the step `H - j` computed from the history `hist` (backward
recursion; `j = 0` is the terminal step, with value `0`), clipped at `e^{β (k + 1)}` (`β > 0`)
or `1` (`β < 0`) where `k` is the number of steps after the current step. -/
noncomputable def cert (r : Fin H → S → A → ℝ) (β δ : ℝ) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) (j : ℕ) : S → ℝ :=
  Nat.rec (motive := fun _ ↦ S → ℝ) (fun _ ↦ 0) (certStep r β δ hist) j

/-- The stopping rule of Entropic-BPI: `π^{t+1} G_1(s₁) ≤ (e^{βε} - 1) e^{-βε} Z̃_1(s₁)` if
`β > 0`, `π^{t+1} G_1(s₁) ≤ (1 - e^{βε}) Z̲_1(s₁)` if `β < 0`. -/
noncomputable def stopCond (r : Fin H → S → A → ℝ) (β δ ε : ℝ) (s₁ : S) {t : ℕ}
    (hist : Hist Unit (Policy S A H) (Traj S H) t) : Prop :=
  if 0 < β then
    cert r β δ hist H s₁ ≤ (Real.exp (β * ε) - 1) / Real.exp (β * ε) * (optZ r β δ hist H).1 s₁
  else cert r β δ hist H s₁ ≤ (1 - Real.exp (β * ε)) * (optZ r β δ hist H).2 s₁

lemma measurable_greedy_fst (r : Fin H → S → A → ℝ) (β δ : ℝ) (n : ℕ) :
    Measurable fun p : Hist Unit (Policy S A H) (Traj S H) n × Unit ↦ greedy r β δ p.1 := sorry

lemma measurable_greedy_snd (r : Fin H → S → A → ℝ) (β δ : ℝ) :
    Measurable fun h : Σ n : ℕ, Hist Unit (Policy S A H) (Traj S H) n ↦ greedy r β δ h.2 := sorry

lemma measurableSet_stopCond (r : Fin H → S → A → ℝ) (β δ ε : ℝ) (s₁ : S) :
    MeasurableSet {h : Σ n : ℕ, Hist Unit (Policy S A H) (Traj S H) n | stopCond r β δ ε s₁ h.2} := sorry

/-- **Algorithm 1** (Entropic-BPI) with known rewards `r`, risk parameter `β`, confidence `δ`,
accuracy `ε` and initial state `s₁`: at each episode, play the greedy policy of the optimistic
backups computed from the past episodes; stop when the certificate of the greedy policy is small
enough, and output the greedy policy. -/
noncomputable def entropicBPI (r : Fin H → S → A → ℝ) (β δ ε : ℝ) (s₁ : S) : BPIAlg S A H where
  alg := detAlgorithm (fun _ p ↦ greedy r β δ p.1) (measurable_greedy_fst r β δ)
  stopSet := {h | stopCond r β δ ε s₁ h.2}
  measurableSet_stopSet := measurableSet_stopCond r β δ ε s₁
  output := Kernel.deterministic (fun h ↦ greedy r β δ h.2) (measurable_greedy_snd r β δ)

end Algorithm
end Essakine2026Tight
end

-- ═══ EV2026.UpperBound ═══
section
open MeasureTheory ProbabilityTheory Learning Learning.MDP.Episodic
open scoped ENNReal
namespace Essakine2026Tight
variable {S A : Type*} [Fintype S] [Fintype A] [DecidableEq S] [DecidableEq A] [Nonempty A] [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A] [MeasurableSingletonClass A] {H : ℕ}

/-- **Theorem 4, first part** (Essakine, Vernade 2026; PAC property). For every reward function
`r` with values in `[0, 1]`, `β ≠ 0`, `δ ∈ (0, 1)` and `ε ∈ (0, 2 / (|β| H S)]`, Entropic-BPI
with parameters `r, β, δ, ε` and initial state `s₁` is `(ε, δ)`-PAC for entropic best-policy
identification on the class of MDPs with reward function `r`. -/
theorem isEntropicPAC_entropicBPI (r : Fin H → S → A → ℝ) (hr : ∀ h s a, r h s a ∈ Set.Icc 0 1)
    {β δ ε : ℝ} (hβ : β ≠ 0) (hδ : δ ∈ Set.Ioo 0 1)
    (hε : ε ∈ Set.Ioc 0 (2 / (|β| * H * Fintype.card S))) (s₁ : S) :
    IsEntropicPAC (entropicBPI r β δ ε s₁) r β ε δ s₁ := sorry

end Essakine2026Tight
end
