import Mathlib.MeasureTheory.MeasurableSpace.Embedding
import Mathlib.Order.Restriction
import Mathlib.Probability.HasCondDistrib
import Mathlib.Probability.HasLaw
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.Probability.Kernel.IonescuTulcea.Maps
import Mathlib.Probability.Kernel.IonescuTulcea.Traj
import Mathlib.Probability.Process.HittingTime
import Mathlib.Probability.Kernel.Basic
import Mathlib.MeasureTheory.Measure.Real
import Mathlib.Probability.Kernel.Composition.Lemmas
import Mathlib.MeasureTheory.Function.EssSup
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Data.Nat.Log
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.InformationTheory.KullbackLeibler.DataProcessing
import Mathlib.Probability.Distributions.Bernoulli
import Mathlib.MeasureTheory.Measure.Decomposition.Lebesgue
import Mathlib.Analysis.SpecialFunctions.BinaryEntropy
import Mathlib.Analysis.Convex.Jensen
import Mathlib.Topology.Instances.ENNReal.Lemmas
import Mathlib.Data.ENat.SuccOrder
import Mathlib.Probability.Moments.Variance
import Mathlib.Algebra.Order.Field.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Ring
import Mathlib.Probability.Kernel.Composition.IntegralCompProd
import Mathlib.Algebra.BigOperators.Intervals
import Mathlib.Algebra.Order.BigOperators.Group.Finset

/-! # Standalone extraction for `Essakine2026Tight.exists_hardMDP_lowerBound_le_lintegral_stoppingTime`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee (`scripts/make-challenges.py`), with the LML declarations the
statement rests on vendored in below, so that this file is self-contained over Mathlib
(its transitive imports resolve to Mathlib and Lean core only). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Learning.MDP
end Learning.MDP
namespace Learning.MDP.Episodic
end Learning.MDP.Episodic
namespace Learning.MDP.Episodic.EpisodicMDP
end Learning.MDP.Episodic.EpisodicMDP
namespace Essakine2026Tight
end Essakine2026Tight
namespace InformationTheory
end InformationTheory

-- ═══ vendored from LML: LeanMachineLearning.ForMathlib.MeasureTheory.MeasurableSpace.Embedding ═══
-- The declarations of https://github.com/LeanMachineLearning/LML that the statement rests on,
-- copied verbatim (Apache 2.0, Authors: Rémy Degenne, Paulo Rauber) so that this file's imports
-- bottom out in Mathlib. Comparator checks each constant is *identical* to the LML package's.
section
open Finset Preorder
namespace MeasurableEquiv

section Fin

variable {X : ℕ → Type*} [∀ n, MeasurableSpace (X n)]

/-- Measurable equivalence between `Π i : Fin (n + 1), X i` and `Π i : Iic n, X i`. -/
def finSuccPiIic (X : ℕ → Type*) [∀ n, MeasurableSpace (X n)] (n : ℕ) :
    (Π i : Fin (n + 1), X i) ≃ᵐ (Π i : Iic n, X i) where
  toFun h i := h ⟨i.1, Nat.lt_succ_of_le (mem_Iic.mp i.2)⟩
  invFun h i := h ⟨i.1, mem_Iic.mpr (Nat.le_of_lt_succ i.2)⟩
  left_inv _ := rfl
  right_inv _ := rfl
  measurable_toFun := .of_eval fun _ ↦ measurable_pi_apply _
  measurable_invFun := .of_eval fun _ ↦ measurable_pi_apply _

end Fin

end MeasurableEquiv
end

-- ═══ vendored from LML: LeanMachineLearning.ForMathlib.Probability.Kernel.IonescuTulcea.Traj ═══
section
open Filter Finset Function MeasurableEquiv MeasurableSpace MeasureTheory Preorder ProbabilityTheory

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {P : Measure Ω}
  {X : ℕ → Type*} [∀ n, MeasurableSpace (X n)]
  {κ : (n : ℕ) → Kernel (Π i : Iic n, X i) (X (n + 1))} [∀ n, IsMarkovKernel (κ n)]
  {μ₀ : Measure (X 0)} [IsProbabilityMeasure μ₀]

namespace ProbabilityTheory.Kernel

section FinTraj

variable {κ' : (n : ℕ) → Kernel (Π i : Fin n, X i) (X n)} [∀ n, IsMarkovKernel (κ' n)]

/-- Kernels indexed by `Iic n` (as needed for `Kernel.traj`), obtained from kernels indexed by
`Fin n`: the kernel `κ' (n + 1)` on `Π i : Fin (n + 1), X i` is seen as a kernel on
`Π i : Iic n, X i`. -/
noncomputable
def iicOfFin (κ' : (n : ℕ) → Kernel (Π i : Fin n, X i) (X n)) (n : ℕ) :
    Kernel (Π i : Iic n, X i) (X (n + 1)) :=
  (κ' (n + 1)).comap (MeasurableEquiv.finSuccPiIic X n).symm (by fun_prop)

instance (n : ℕ) : IsMarkovKernel (iicOfFin κ' n) := by unfold iicOfFin; infer_instance

/-- Measure on trajectories `Π n, X n` built from kernels `κ' n : Kernel (Π i : Fin n, X i) (X n)`
describing the law of the coordinate `n` given the `n` previous coordinates.
The initial measure is `κ' 0 default`. -/
noncomputable
def trajMeasureFin (κ' : (n : ℕ) → Kernel (Π i : Fin n, X i) (X n)) [∀ n, IsMarkovKernel (κ' n)] :
    Measure (Π n, X n) :=
  trajMeasure (κ' 0 default) (iicOfFin κ')
deriving IsProbabilityMeasure

end FinTraj

end ProbabilityTheory.Kernel
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Algorithm ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The observation of a round. -/
def Round.obs (r : Round 𝓞 𝓐 𝓨) : 𝓞 := r.1
/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1
/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.obs n) := env.isMarkovKernel_obs n
instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) :=
  env.isMarkovKernel_feedback n

/-- Kernel describing the distribution of the round at time `n` given the history before `n`. -/
noncomputable
def stepKernel (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) :
    Kernel (Hist 𝓞 𝓐 𝓨 n) (Round 𝓞 𝓐 𝓨) :=
  env.obs n ⊗ₖ (alg.policy n ⊗ₖ env.feedback n)
deriving IsMarkovKernel

section IsAlgEnvSeq

variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StationaryEnv ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- An oblivious environment without observations, in which the distribution of the next feedback
depends only on the last action, but in a possibly time-dependent manner. -/
@[simps]
noncomputable
def obliviousEnv (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment Unit 𝓐 𝓨 where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n := (ν n).prodMkLeft _

/-- A stationary environment without observations, in which the distribution of the next feedback
depends only on the last action. -/
noncomputable
def stationaryEnv (ν : Kernel 𝓐 𝓨) [IsMarkovKernel ν] : Environment Unit 𝓐 𝓨 :=
  obliviousEnv fun _ ↦ ν

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Deterministic ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- A deterministic algorithm, which chooses the action given by the function `nextA`.
The initial action is `fun o ↦ nextA 0 (default, o)`. -/
@[simps]
noncomputable
def detAlgorithm (nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐)
    (h_next : ∀ n, Measurable (nextA n)) :
    Algorithm 𝓞 𝓐 𝓨 where
  policy n := Kernel.deterministic (nextA n) (h_next n)

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.IonescuTulceaSpace ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- Measure on the sequence of rounds generated by the algorithm/environment. -/
noncomputable
def trajMeasure (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨) :
    Measure (ℕ → Round 𝓞 𝓐 𝓨) :=
  Kernel.trajMeasureFin (stepKernel alg env)
deriving IsProbabilityMeasure

namespace IT

/-- `obs n` is the observation at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def obs (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓞 := (h n).obs

/-- `action n` is the action pulled at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def action (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓐 := (h n).action

/-- `feedback n` is the feedback at time `n`. This is a random variable on the measurable space
`ℕ → Round 𝓞 𝓐 𝓨`. -/
def feedback (n : ℕ) (h : ℕ → Round 𝓞 𝓐 𝓨) : 𝓨 := (h n).feedback

end IT

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StoppedHistory ═══
section
open MeasureTheory ProbabilityTheory
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}
  {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
  {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)}
  {τ : Ω → WithTop ℕ} {ω : Ω} {n M : ℕ}

/-- The history of the first `n` rounds, as a history of variable length in the sigma type
`Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n`. -/
def sigmaHistory (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) :
    Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  ⟨n, history O X Y n ω⟩

section StoppedHistMeasure

/-- The law of the history stopped by the stopping rule `S`, for the algorithm `alg` in the
environment `env`: the law of the stopped history on the canonical space `trajMeasure alg env`.
This is the law of the stopped history for any algorithm-environment sequence
(`IsAlgEnvSeq.hasLaw_stoppedValue_sigmaHistory`). -/
noncomputable def stoppedHistMeasure (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)) :
    Measure (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n) :=
  (trajMeasure alg env).map
    (stoppedValue (sigmaHistory IT.obs IT.action IT.feedback)
      (hittingAfter (sigmaHistory IT.obs IT.action IT.feedback) S 0))
deriving IsProbabilityMeasure

end StoppedHistMeasure

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.IdentificationAlg ═══
section
open MeasureTheory ProbabilityTheory
open scoped ENat
namespace Learning

variable {𝓞 𝓐 𝓨 𝓓 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {m𝓓 : MeasurableSpace 𝓓} {mΩ : MeasurableSpace Ω}
  {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}

/-- An identification algorithm with outputs in `𝓓`: a sampling rule `alg`, a stopping rule
`stopSet` (the algorithm stops after `n` rounds if the history of these rounds belongs to
`stopSet`) and an output rule `output`, a Markov kernel giving the distribution of the output
given the history of the rounds played. -/
structure IdentAlg (𝓞 𝓐 𝓨 𝓓 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐]
    [MeasurableSpace 𝓨] [MeasurableSpace 𝓓] where
  /-- The sampling rule. -/
  alg : Algorithm 𝓞 𝓐 𝓨
  /-- The stopping rule: the algorithm stops after `n` rounds if the history of these rounds
  belongs to `stopSet`. -/
  stopSet : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)
  /-- The stopping rule is measurable. -/
  measurableSet_stopSet : MeasurableSet stopSet
  /-- The output rule: distribution of the output given the history of the rounds played. -/
  output : Kernel (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n) 𝓓
  /-- The output rule is a Markov kernel. -/
  [isMarkovKernel_output : IsMarkovKernel output]

namespace IdentAlg

variable {A : IdentAlg 𝓞 𝓐 𝓨 𝓓} {env : Environment 𝓞 𝓐 𝓨} {out : Ω → 𝓓} {P : Measure Ω}

instance : IsMarkovKernel A.output := A.isMarkovKernel_output

/-- The stopping time of `A` on the observation, action and feedback processes `O`, `X`, `Y`: the
number of rounds played, that is the first `n` such that the history of the first `n` rounds
belongs to the stopping rule `A.stopSet` (`⊤` if there is none). -/
noncomputable def stoppingTime (A : IdentAlg 𝓞 𝓐 𝓨 𝓓)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    Ω → ℕ∞ :=
  hittingAfter (sigmaHistory O X Y) A.stopSet 0

/-- The history of the rounds played by an identification algorithm `A`, as a history of variable
length: the history stopped at `A.stoppingTime O X Y`
(the history of an arbitrary number of rounds if `A` never stops). -/
noncomputable def stoppedHist (A : IdentAlg 𝓞 𝓐 𝓨 𝓓)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    Ω → Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  stoppedValue (sigmaHistory O X Y) (A.stoppingTime O X Y)

/-- `(O, X, Y, out)` is a *run* of the identification algorithm `A` in the environment `env` on
the probability space `(Ω, P)`: the observation, action and feedback processes `O`, `X`, `Y` form
an algorithm-environment sequence for the sampling rule `A.alg` and `env`, and the output `out` has
conditional law `A.output` given the history at the stopping time. -/
structure IsRun (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Environment 𝓞 𝓐 𝓨)
    (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (out : Ω → 𝓓)
    (P : Measure Ω := by volume_tac) [IsFiniteMeasure P] : Prop where
  /-- The actions and feedbacks are generated by the sampling rule in the environment. -/
  isAlgEnvSeq : IsAlgEnvSeq O X Y A.alg env P
  /-- The output is drawn from the output rule applied to the history at the stopping time. -/
  hasCondDistrib_output : HasCondDistrib out (A.stoppedHist O X Y) A.output P

/-- The law of the output of an identification algorithm in an environment. -/
noncomputable def outputMeasure (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Environment 𝓞 𝓐 𝓨) : Measure 𝓓 :=
  A.output ∘ₘ stoppedHistMeasure A.alg env A.stopSet
deriving IsProbabilityMeasure

section IsPAC

/-- `A` is *PAC at level `δ`* for the family of environments `env : Θ → Environment 𝓞 𝓐 𝓨` and
the predicate `bad : Θ → 𝓓 → Prop` if, for every `θ`, the output of `A` in `env θ` is
`bad θ` with probability at most `δ`.
See `IsPAC.measureReal_not_good_of_isRun` for the corresponding statement about any run of `A`. -/
def IsPAC {Θ : Type*} (A : IdentAlg 𝓞 𝓐 𝓨 𝓓) (env : Θ → Environment 𝓞 𝓐 𝓨)
    (bad : Θ → 𝓓 → Prop) (δ : ℝ) : Prop :=
  ∀ θ, (A.outputMeasure (env θ)).real {d | bad θ d} ≤ δ

end IsPAC

end IdentAlg

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.ForMathlib.MeasureTheory.Order.MeasurableArg ═══
section
open Finset

variable {ι α : Type*} [LinearOrder α] [Fintype ι] [Nonempty ι] (f : ι → α)

namespace Function

/-- The maximum value of a tuple. -/
abbrev max : α := univ.sup' univ_nonempty f

/-- The minimum value of a tuple. -/
abbrev min : α := univ.inf' univ_nonempty f

end Function

lemma exists_argmax : ∃ i, f i = f.max := sorry

lemma exists_argmin : ∃ i, f i = f.min := sorry

/-- The index of the maximum value of a tuple. -/
noncomputable def argmax := (exists_argmax f).choose

/-- The index of the minimum value of a tuple. -/
noncomputable def argmin := (exists_argmin f).choose

end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Basic ═══
section
open MeasureTheory ProbabilityTheory Learning

/-- Markov decision process with state space `𝓢`, action space `𝓐`, and reward space `𝓡`, described
by a transition kernel `P : Kernel (𝓢 × 𝓐) 𝓢` and a reward kernel `R : Kernel (𝓢 × 𝓐) 𝓡`.
See `MDP.env` for the environment associated with the MDP. -/
structure MDP (𝓢 𝓐 𝓡 : Type*) [MeasurableSpace 𝓢] [MeasurableSpace 𝓐] [MeasurableSpace 𝓡] where
  /-- The transition kernel: the law of the next state given the current state and action. -/
  P : Kernel (𝓢 × 𝓐) 𝓢
  /-- The transition kernel is a Markov kernel. -/
  [hP : IsMarkovKernel P]
  /-- The reward kernel: the law of the reward given the current state and action. -/
  R : Kernel (𝓢 × 𝓐) 𝓡
  /-- The reward kernel is a Markov kernel. -/
  [hR : IsMarkovKernel R]

namespace Learning.MDP
variable {𝓢 𝓐 𝓡 : Type*} {m𝓢 : MeasurableSpace 𝓢} {m𝓐 : MeasurableSpace 𝓐} {m𝓡 : MeasurableSpace 𝓡}

instance (M : MDP 𝓢 𝓐 𝓡) : IsMarkovKernel M.R := M.hR

/-- The state and the action of the last round of a history of `n + 1` rounds. -/
def lastObsAction (n : ℕ) (h : Hist 𝓢 𝓐 𝓡 (n + 1)) : 𝓢 × 𝓐 :=
  ((h (Fin.last n)).obs, (h (Fin.last n)).action)

lemma measurable_lastObsAction (n : ℕ) :
    Measurable (lastObsAction (𝓢 := 𝓢) (𝓐 := 𝓐) (𝓡 := 𝓡) n) := sorry

/-- The current state and the action of a round, from the history, the observation and the
action. -/
def obsAction (n : ℕ) (p : (Hist 𝓢 𝓐 𝓡 n × 𝓢) × 𝓐) : 𝓢 × 𝓐 := (p.1.2, p.2)

lemma measurable_obsAction (n : ℕ) : Measurable (obsAction (𝓢 := 𝓢) (𝓐 := 𝓐) (𝓡 := 𝓡) n) := sorry

/-- The observation kernel of the environment of `M` with initial state distribution `μ₀`: the
initial state is drawn from `μ₀`, and the state of round `n + 1` from `M.P` applied to the state
and action of round `n`. -/
noncomputable def envObs (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) (n : ℕ) : Kernel (Hist 𝓢 𝓐 𝓡 n) 𝓢 :=
  Nat.rec (motive := fun n ↦ Kernel (Hist 𝓢 𝓐 𝓡 n) 𝓢) (Kernel.const _ μ₀)
    (fun n _ ↦ M.P.comap (lastObsAction n) (measurable_lastObsAction n)) n

lemma isMarkovKernel_envObs (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) [IsProbabilityMeasure μ₀] (n : ℕ) :
    IsMarkovKernel (envObs M μ₀ n) := sorry

instance (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) [IsProbabilityMeasure μ₀] (n : ℕ) :
    IsMarkovKernel (envObs M μ₀ n) :=
  isMarkovKernel_envObs M μ₀ n

/-- The environment of the MDP `M` with initial state distribution `μ₀`: the observation of a
round is the current state (drawn from `μ₀` at the first round, then from `M.P (s, a)` for the
state `s` and action `a` of the previous round), and the feedback is the reward, drawn from
`M.R (s, a)`. -/
protected noncomputable def env (M : MDP 𝓢 𝓐 𝓡) (μ₀ : Measure 𝓢) [IsProbabilityMeasure μ₀] :
    Environment 𝓢 𝓐 𝓡 where
  obs := envObs M μ₀
  feedback n := M.R.comap (obsAction n) (measurable_obsAction n)

lemma measurable_policyAlg_next {π : 𝓢 → 𝓐} (hπ : Measurable π) (n : ℕ) :
    Measurable fun p : Hist 𝓢 𝓐 𝓡 n × 𝓢 ↦ π p.2 := sorry

/-- The stationary deterministic policy `π` as an algorithm: it plays `π s` in the current
state `s`. -/
noncomputable def policyAlg (π : 𝓢 → 𝓐) (hπ : Measurable π) : Algorithm 𝓢 𝓐 𝓡 :=
  detAlgorithm (fun _ p ↦ π p.2) (measurable_policyAlg_next hπ)

/-- The law of the trajectory of the policy `π` started at the state `s`: `E^π_s`. -/
noncomputable def policyMeasure (M : MDP 𝓢 𝓐 𝓡) (π : 𝓢 → 𝓐) (hπ : Measurable π) (s : 𝓢) :
    Measure (ℕ → Round 𝓢 𝓐 𝓡) :=
  trajMeasure (policyAlg π hπ) (M.env (Measure.dirac s))

variable [NormedAddCommGroup 𝓡] [NormedSpace ℝ 𝓡]
end Learning.MDP
end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Episodic ═══
section
open MeasureTheory ProbabilityTheory Finset Learning Learning.MDP
namespace Learning.MDP.Episodic
variable {S A : Type*} [MeasurableSpace S] [MeasurableSpace A]

/-- A finite-horizon MDP: the transition kernels `trans h : Kernel (S × A) S` and the reward
kernels `reward h : Kernel (S × A) ℝ` at each step `h : ℕ`. -/
structure EpisodicMDP (S A : Type*) [MeasurableSpace S] [MeasurableSpace A] where
  /-- The transition kernel at step `h`: the law of the next state. -/
  trans : ℕ → Kernel (S × A) S
  /-- The transition kernels are Markov kernels. -/
  [isMarkovKernel_trans : ∀ h, IsMarkovKernel (trans h)]
  /-- The reward kernel at step `h`: the law of the reward. -/
  reward : ℕ → Kernel (S × A) ℝ
  /-- The reward kernels are Markov kernels. -/
  [isMarkovKernel_reward : ∀ h, IsMarkovKernel (reward h)]

omit [MeasurableSpace S] [MeasurableSpace A] in
/-- The stationary policy of the time-augmented state space `S × ℕ` associated with the policy
`π : ℕ → S → A`: the action `π h s` at the state `(s, h)`. -/
def augPolicy (π : ℕ → S → A) (p : S × ℕ) : A := π p.2 p.1

lemma measurable_augPolicy {π : ℕ → S → A} (hπ : ∀ h, Measurable (π h)) :
    Measurable (augPolicy π) := sorry

/-- A deterministic `H`-step policy: the action `π h s` played at the step `h : Fin H` in the
state `s`. -/
abbrev Policy (S A : Type*) (H : ℕ) := Fin H → S → A

/-- The state sequence `s_0, …, s_H` of an episode of horizon `H`. -/
abbrev Traj (S : Type*) (H : ℕ) := Fin (H + 1) → S

section Extend
variable [Nonempty A] {H : ℕ}

omit [MeasurableSpace S] [MeasurableSpace A] in
/-- The `H`-step policy `π` extended to all steps by a fixed action beyond the horizon. -/
noncomputable def Policy.extend (π : Policy S A H) (h : ℕ) (s : S) : A :=
  if hh : h < H then π ⟨h, hh⟩ s else Classical.arbitrary A

end Extend
namespace EpisodicMDP
variable (M : EpisodicMDP S A)

/-- The rewards of `M` are the deterministic reward function `r`: the reward of `(s, a)` at step
`h` is `r h s a` almost surely. -/
def HasRewardFn (r : ℕ → S → A → ℝ) : Prop := ∀ h s a, M.reward h (s, a) = Measure.dirac (r h s a)

/-- The transition function of the time-augmented MDP: from `(s, h)` with action `a`, the next
augmented state is `(s', h + 1)` with `s' ∼ M.trans h (s, a)`. -/
noncomputable def augTransFun (p : (S × ℕ) × A) : Measure (S × ℕ) :=
  (M.trans p.1.2 (p.1.1, p.2)).map fun s' ↦ (s', p.1.2 + 1)

lemma measurable_augTransFun : Measurable M.augTransFun := sorry

/-- The transition kernel of the time-augmented MDP. -/
noncomputable def augTrans : Kernel ((S × ℕ) × A) (S × ℕ) :=
  ⟨M.augTransFun, M.measurable_augTransFun⟩

lemma isProbabilityMeasure_augTrans (p : (S × ℕ) × A) : IsProbabilityMeasure (M.augTrans p) := sorry

instance : IsMarkovKernel M.augTrans := ⟨M.isProbabilityMeasure_augTrans⟩

/-- The reward function of the time-augmented MDP: `M.reward h (s, a)` at `(s, h)`. -/
noncomputable def augRewardFun (p : (S × ℕ) × A) : Measure ℝ := M.reward p.1.2 (p.1.1, p.2)

lemma measurable_augRewardFun : Measurable M.augRewardFun := sorry

/-- The reward kernel of the time-augmented MDP. -/
noncomputable def augReward : Kernel ((S × ℕ) × A) ℝ :=
  ⟨M.augRewardFun, M.measurable_augRewardFun⟩

lemma isProbabilityMeasure_augReward (p : (S × ℕ) × A) :
    IsProbabilityMeasure (M.augReward p) := sorry

instance : IsMarkovKernel M.augReward := ⟨M.isProbabilityMeasure_augReward⟩

/-- The stationary MDP on the time-augmented state space `S × ℕ` which embeds the finite-horizon
MDP `M`. -/
noncomputable def augmented : MDP (S × ℕ) A ℝ where
  P := M.augTrans
  R := M.augReward

end EpisodicMDP

open Classical in
/-- The law of the trajectory of the time-augmented MDP under the policy `π` started at the
augmented state `p₀ = (s, h)`: the law of `((S_{h+k}, h + k), A_{h+k}, R_{h+k})_{k ≥ 0}` from the
state `s` at the step `h`. It is `0` if `π` is not measurable at every step. -/
noncomputable def stepLaw (M : EpisodicMDP S A) (π : ℕ → S → A) (p₀ : S × ℕ) :
    Measure (ℕ → Round (S × ℕ) A ℝ) :=
  if hπ : ∀ k, Measurable (π k) then
    M.augmented.policyMeasure (augPolicy π) (measurable_augPolicy hπ) p₀
  else 0

omit [MeasurableSpace S] [MeasurableSpace A] in
/-- The return `∑_{k < n} R_k` of the first `n` rounds of a trajectory of the time-augmented
MDP. -/
def episodeReturn (n : ℕ) (traj : ℕ → Round (S × ℕ) A ℝ) : ℝ :=
  ∑ k ∈ range n, IT.feedback k traj

omit [MeasurableSpace S] [MeasurableSpace A] in
/-- The states `s_0, …, s_H` of a trajectory of the time-augmented MDP. -/
def episodeStates (H : ℕ) (traj : ℕ → Round (S × ℕ) A ℝ) : Traj S H :=
  fun h ↦ (IT.obs h traj).1

section EpisodeEnv
variable (M : EpisodicMDP S A) (H : ℕ)

/-- The law of the state sequence of the episode of horizon `H` played with the policy `π`
from `s₁`. -/
noncomputable def statesLaw (s₁ : S) (π : ℕ → S → A) : Measure (Traj S H) :=
  (stepLaw M π (s₁, 0)).map (episodeStates H)

variable [Finite S] [Countable A] [MeasurableSingletonClass S] [MeasurableSingletonClass A] [Nonempty A]

omit [MeasurableSingletonClass S] in
lemma measurable_statesLaw_extend (s₁ : S) :
    Measurable fun π : Policy S A H ↦ statesLaw M H s₁ π.extend := sorry

/-- The kernel from `H`-step policies to the law of the state sequence of the episode played with
the policy from `s₁`. -/
noncomputable def statesKernel (s₁ : S) : Kernel (Policy S A H) (Traj S H) :=
  ⟨fun π ↦ statesLaw M H s₁ π.extend, measurable_statesLaw_extend M H s₁⟩

lemma isProbabilityMeasure_statesKernel (s₁ : S) (π : Policy S A H) :
    IsProbabilityMeasure (statesKernel M H s₁ π) := sorry

instance (s₁ : S) : IsMarkovKernel (statesKernel M H s₁) :=
  ⟨isProbabilityMeasure_statesKernel M H s₁⟩

/-- The episodic environment with horizon `H` and the fixed initial state `s₁`, in which the
learner observes the states of the episode only (the rewards being known): at each round, the
learner plays an `H`-step policy and observes the states. -/
noncomputable def statesEnv (s₁ : S) : Environment Unit (Policy S A H) (Traj S H) :=
  stationaryEnv (statesKernel M H s₁)

end EpisodeEnv

omit [MeasurableSpace S] [MeasurableSpace A] in
/-- A best-policy identification algorithm: an identification algorithm playing an `H`-step
policy at each episode, observing the states, and outputting an `H`-step policy. -/
abbrev BPIAlg (S A : Type*) [MeasurableSpace S] [MeasurableSpace A] (H : ℕ) :=
  IdentAlg Unit (Policy S A H) (Traj S H) (Policy S A H)

end Learning.MDP.Episodic
end

-- ═══ LeanMachineLearning.ReinforcementLearning.MDP.Entropic ═══
section
open MeasureTheory ProbabilityTheory Finset Learning Learning.MDP
namespace Learning.MDP.Episodic
variable {S A : Type*} [MeasurableSpace S] [MeasurableSpace A]

/-- The exponential value `Z^π_h(s) = E[exp(β R_h) | S_h = s]` with the horizon `H`, where `R_h`
is the return of the `H - h` steps from `h`. -/
noncomputable def expValue (M : EpisodicMDP S A) (H : ℕ) (β : ℝ) (π : ℕ → S → A) (h : ℕ)
    (s : S) : ℝ :=
  ∫ traj, Real.exp (β * episodeReturn (H - h) traj) ∂(stepLaw M π (s, h))

/-- The entropic value `V^π_h(s) = β⁻¹ log E[exp(β R_h) | S_h = s]`. -/
noncomputable def entropicValue (M : EpisodicMDP S A) (H : ℕ) (β : ℝ) (π : ℕ → S → A)
    (h : ℕ) (s : S) : ℝ :=
  β⁻¹ * Real.log (expValue M H β π h s)

/-- The optimal entropic value `V*_h(s) = ⨆ π, V^π_h(s)`, the supremum over all the policies
`π : ℕ → S → A` which are measurable at every step. -/
noncomputable def optEntropicValue (M : EpisodicMDP S A) (H : ℕ) (β : ℝ) (h : ℕ) (s : S) : ℝ :=
  ⨆ π : {π : ℕ → S → A // ∀ k, Measurable (π k)}, entropicValue M H β π h s

/-- The maximal achievable return `G_max(M) = ⨆ π, ess sup R_0` of an episode of horizon `H`
from the initial state `s₁`, over all the policies which are measurable at every step. -/
noncomputable def maxReturn (M : EpisodicMDP S A) (H : ℕ) (s₁ : S) : ℝ :=
  ⨆ π : {π : ℕ → S → A // ∀ k, Measurable (π k)}, essSup (episodeReturn H) (stepLaw M π (s₁, 0))

variable [Finite S] [Countable A] [MeasurableSingletonClass S] [MeasurableSingletonClass A] [Nonempty A] {H : ℕ}

/-- `𝒜` is `(ε, δ)`-PAC for best-policy identification under the entropic risk measure with
parameter `β`, for the known reward function `r`, from the initial state `s₁`: for every MDP
with reward function `r`, the output `π̂` of `𝒜` in its states-only environment satisfies
`V*_0(s₁) - V^π̂_0(s₁) > ε` with probability at most `δ`. -/
def IsEntropicPAC (𝒜 : BPIAlg S A H) (r : ℕ → S → A → ℝ) (β ε δ : ℝ) (s₁ : S) : Prop :=
  𝒜.IsPAC (fun M : {M : EpisodicMDP S A // M.HasRewardFn r} ↦ statesEnv M.1 H s₁)
    (fun M π ↦ ε < optEntropicValue M.1 H β 0 s₁ - entropicValue M.1 H β π.extend 0 s₁) δ

end Learning.MDP.Episodic
end

-- ═══ EV2026.Constants ═══
section
namespace Essakine2026Tight

/-- The depth `d = ⌈log_A((S - 3)(A - 1) + 1)⌉` of the tree of the hard instances
(Assumption 1 is `H ≥ 3 d`). -/
def treeDepth (S A : ℕ) : ℕ := Nat.clog A ((S - 3) * (A - 1) + 1)

/-- The effective horizon `H' = H - ⌊H/3⌋ - d` of the hard instances: the number of steps at
which a reward can be collected. -/
def effHorizon (S A H : ℕ) : ℕ := H - H / 3 - treeDepth S A

/-- **Condition A** (small-`ε` regime of the lower bound), for the effective horizon `H'`: with
`c = e^{|β| H'} - 1` and `q = e^{|β| ε}`, `q - 1 ≤ c (2 c + 1) / (4 (3 c + 2))` if `β > 0` and
`q - 1 ≤ c / (10 c + 8)` if `β < 0`. This is the paper's condition stated with the effective
horizon `H'` of the construction instead of `H` and with the margin `p₊ ≤ (1 + p₋) / 2`, which
the paper's bound on the binary divergence needs (blueprint, chapter "Lower bound",
`def:condition_a`). -/
noncomputable def ConditionA (β : ℝ) (H' : ℕ) (ε : ℝ) : Prop :=
  let c := Real.exp (|β| * H') - 1
  if 0 < β then
    Real.exp (|β| * ε) - 1 ≤ c * ((2 : ℕ) * c + 1) / ((4 : ℕ) * ((3 : ℕ) * c + (2 : ℕ)))
  else Real.exp (|β| * ε) - 1 ≤ c / ((10 : ℕ) * c + (8 : ℕ))

/-- The variance factor `V_G = (e^{|β| G} - 1)² / e^{|β| G}` of the maximal return `G`. -/
noncomputable def varianceFactor (β G : ℝ) : ℝ :=
  (Real.exp (|β| * G) - 1) ^ 2 / Real.exp (|β| * G)

/-- The lower bound of Theorem 3 on the expected number of episodes, for the maximal return
`G`: `(1/5000) V_G e^{2 min(β, 0) ε} S A H log(1/δ) / (e^{|β| ε} - 1)²`. -/
noncomputable def lowerBound (S A H : ℕ) (β ε δ G : ℝ) : ℝ :=
  1 / (5000 : ℕ) * varianceFactor β G
    * (Real.exp ((2 : ℕ) * min β 0 * ε) * (S * A * H : ℕ) / (Real.exp (|β| * ε) - 1) ^ 2)
    * Real.log (1 / δ)

end Essakine2026Tight
end

-- ═══ EV2026.LowerBound ═══
section
open MeasureTheory ProbabilityTheory Learning Learning.MDP.Episodic InformationTheory
open scoped ENNReal
universe u v
namespace Essakine2026Tight

/-- **Theorem 3** (Essakine, Vernade 2026). For finite state and action spaces with `S ≥ 6`,
`A ≥ 2`, a horizon `H ≥ 3 d` with `d = ⌈log_A((S - 3)(A - 1) + 1)⌉` (Assumption 1), `β ≠ 0`,
`δ ∈ (0, 1/16]` and `ε > 0` satisfying Condition A for the effective horizon
`H' = H - ⌊H/3⌋ - d`, there are a reward function `r₀` with
values in `[0, 1]`, an MDP `M₀` with reward function `r₀` and an initial state `s₁` such that
every algorithm which is `(ε, δ)`-PAC for entropic best-policy identification with reward
function `r₀` satisfies, in every run on `M₀`,
`E[τ] ≥ (1/5000) (e^{|β| G_max(M₀)} - 1)² e^{-|β| G_max(M₀)} e^{2 min(β, 0) ε} S A H log(1/δ) /
(e^{|β| ε} - 1)²`. -/
theorem exists_hardMDP_lowerBound_le_lintegral_stoppingTime
    {S A : Type u} [Fintype S] [Fintype A] [Nonempty A]
    [MeasurableSpace S] [MeasurableSingletonClass S] [MeasurableSpace A]
    [MeasurableSingletonClass A] (H : ℕ)
    (hS : 6 ≤ Fintype.card S) (hA : 2 ≤ Fintype.card A)
    (hH : 3 * treeDepth (Fintype.card S) (Fintype.card A) ≤ H)
    {β : ℝ} (hβ : β ≠ 0) {δ : ℝ} (hδ : δ ∈ Set.Ioc 0 (1 / 16)) {ε : ℝ} (hε : 0 < ε)
    (hcond : ConditionA β (effHorizon (Fintype.card S) (Fintype.card A) H) ε) :
    ∃ (r₀ : ℕ → S → A → ℝ) (M₀ : EpisodicMDP S A) (s₁ : S),
      (∀ h s a, r₀ h s a ∈ Set.Icc 0 1) ∧ M₀.HasRewardFn r₀ ∧
      ∀ 𝒜 : BPIAlg S A H, IsEntropicPAC 𝒜 r₀ β ε δ s₁ →
        ∀ {Ω : Type v} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
          (X : ℕ → Ω → Policy S A H) (Y : ℕ → Ω → Traj S H) (out : Ω → Policy S A H),
          𝒜.IsRun (statesEnv M₀ H s₁) (fun _ _ ↦ ()) X Y out P →
          ENNReal.ofReal (lowerBound (Fintype.card S) (Fintype.card A) H β ε δ
              (maxReturn M₀ H s₁)) ≤
            ∫⁻ ω, (𝒜.stoppingTime (fun _ _ ↦ ()) X Y ω : ℝ≥0∞) ∂P := sorry

end Essakine2026Tight
end
