/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import LeanMachineLearning.ForMathlib.MeasureTheory.MeasurableSpace.Sigma
public import LeanMachineLearning.ForMathlib.MeasureTheory.Measurable
public import Essakine2026Tight.Mathlib.MeasureTheory.MeasurableSpace.PiFinSuccProd
public import LeanMachineLearning.ForMathlib.Probability.Process.HittingTime
public import Essakine2026Tight.Mathlib.Probability.CondDistrib
public import Essakine2026Tight.Mathlib.Probability.Process.HittingTime
public import Mathlib.Data.ENat.SuccOrder

/-!
# Prefixes of a process stopped at a stopping time

For a process `Z : (n : ℕ) → Ω → X n` with values in a family of measurable spaces `X n`,
`finPrefix Z n ω = (Z 0 ω, …, Z (n - 1) ω) : Π i : Fin n, X i` is the prefix of length `n` of
the path of `Z`, and `sigmaPrefix Z n ω = ⟨n, finPrefix Z n ω⟩` is the same prefix as a finite
sequence of variable length, in `Σ n : ℕ, Π i : Fin n, X i` (a process with values in a single
space `R` is the case of the constant family `fun _ ↦ R`).

The *prefix filtration* `prefixFiltration Z hZ` is the filtration generated by the prefixes:
`prefixFiltration Z hZ n` is the σ-algebra generated by the prefix of length `n`, the information
available *before* step `n`. A stopping time `τ : Ω → WithTop ℕ` of this filtration (Mathlib's
`IsStoppingTime`) decides whether to stop after `n` steps in terms of the first `n` steps only;
the events `{τ ≤ n}` and `{n < τ}` are then preimages of measurable sets by the prefix of length
`n` (`IsStoppingTime.exists_measurableSet_preimage_finPrefix`), so that conditional laws given
the prefix of length `n` survive the restriction to `{n < τ}`
(`HasCondDistrib.restrict_lt_of_isStoppingTime`). The *stopped prefix*
`stoppedValue (sigmaPrefix Z) τ` (Mathlib) is the prefix of length `τ`, and
`stoppedProcess (sigmaPrefix Z) τ M` is the prefix of length `min τ M`, the prefix stopped at
time `M`. The truncation `truncFin M` of a finite sequence of variable length to its first `M`
terms relates the two:
`truncFin M ∘ stoppedValue (sigmaPrefix Z) τ = stoppedProcess (sigmaPrefix Z) τ M` when `τ < ⊤`
(`truncFin_stoppedValue_sigmaPrefix`), so that the law of the prefix stopped at time `M` is the
image of the law of the stopped prefix by the truncation
(`HasLaw.stoppedProcess_sigmaPrefix`). The law of the prefix stopped at time `M` splits according
to whether `τ ≤ M` (`map_stoppedProcess_sigmaPrefix_eq_add`,
`map_stoppedProcess_sigmaPrefix_succ_eq_add`), and the law of the prefix of length `n + 1` is
the composition-product of the law of the prefix of length `n` with the conditional law of
`Z n` given it (`map_finPrefix_succ_of_hasCondDistrib`). These are the inputs of the chain rule
for the Kullback–Leibler divergence at a stopping time
(`Essakine2026Tight.Mathlib.InformationTheory.KLStoppedPrefix`).

A *stopping rule* is a measurable set `S` of finite sequences of variable length: the process is
stopped after `n` steps if its prefix of length `n` belongs to `S`. The number of steps
`hittingAfter (sigmaPrefix Z) S 0` (Mathlib's hitting time) is the stopping time of the rule
(`lt_hittingAfter_sigmaPrefix_iff`, `hittingAfter_sigmaPrefix_eq_coe_iff`); it is a stopping
time of the prefix filtration (`isStoppingTime_hittingAfter_sigmaPrefix`), and every stopping
time of the prefix filtration is of this form (`IsStoppingTime.exists_eq_hittingAfter_sigmaPrefix`).
The prefix at that time is `hittingValue (sigmaPrefix Z) S 0` and the prefix stopped at time `M`
by the rule is
`hittingProcess (sigmaPrefix Z) S 0 M` (`Essakine2026Tight.Mathlib.Probability.Process.HittingTime`;
their measurability is `measurable_hittingValue_sigmaPrefix`,
`measurable_hittingProcess_sigmaPrefix`).

Time is `0`-indexed: the prefix of length `n` records the steps `0, …, n - 1`, and the decision
to stop after `n` steps depends on these steps only.
-/

@[expose] public section

open MeasureTheory Finset

namespace ProbabilityTheory

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {X : ℕ → Type*} [∀ n, MeasurableSpace (X n)]
  {Z : (n : ℕ) → Ω → X n} {S : Set (Σ n : ℕ, Π i : Fin n, X i)} {τ : Ω → WithTop ℕ} {ω : Ω}
  {n M : ℕ}

/-- The prefix of length `n` of the path of the process `Z`: the values `Z 0, …, Z (n - 1)`. -/
def finPrefix (Z : (n : ℕ) → Ω → X n) (n : ℕ) (ω : Ω) : Π i : Fin n, X i := fun i ↦ Z i ω

/-- The prefix of length `n` of the path of the process `Z`, as a finite sequence of variable
length in `Σ n : ℕ, Π i : Fin n, X i`. -/
def sigmaPrefix (Z : (n : ℕ) → Ω → X n) (n : ℕ) (ω : Ω) : Σ n : ℕ, Π i : Fin n, X i :=
  ⟨n, finPrefix Z n ω⟩

omit [∀ n, MeasurableSpace (X n)] in
/-- The coordinates of the prefix of length `n`. -/
lemma finPrefix_apply (n : ℕ) (ω : Ω) (i : Fin n) : finPrefix Z n ω i = Z i ω := rfl

omit [∀ n, MeasurableSpace (X n)] in
/-- Unfolding lemma for `sigmaPrefix`. -/
lemma sigmaPrefix_apply (n : ℕ) (ω : Ω) : sigmaPrefix Z n ω = ⟨n, finPrefix Z n ω⟩ := rfl

omit [∀ n, MeasurableSpace (X n)] in
/-- The prefix of length `n` has length `n`. -/
@[simp] lemma fst_sigmaPrefix (n : ℕ) (ω : Ω) : (sigmaPrefix Z n ω).1 = n := rfl

/-- The prefix of length `n + 1` is the prefix of length `n` followed by `Z n`. -/
lemma finPrefix_succ (n : ℕ) :
    finPrefix Z (n + 1) =
      (MeasurableEquiv.piFinSuccProd X n).symm ∘ fun ω ↦ (finPrefix Z n ω, Z n ω) := by
  funext ω
  simp only [Function.comp_apply, MeasurableEquiv.piFinSuccProd_symm_apply]
  funext i
  refine Fin.lastCases ?_ (fun i ↦ ?_) i
  · simp [finPrefix]
  · simp [finPrefix]

section StoppingTime

omit [∀ n, MeasurableSpace (X n)] in
/-- The stopping rule `S` has not fired after `n` steps iff none of the prefixes of length
`j ≤ n` belongs to `S`. -/
lemma lt_hittingAfter_sigmaPrefix_iff :
    (n : WithTop ℕ) < hittingAfter (sigmaPrefix Z) S 0 ω ↔ ∀ j ≤ n, sigmaPrefix Z j ω ∉ S := by
  rw [← not_le]
  refine (not_congr (hittingAfter_le_iff (u := sigmaPrefix Z) (s := S) (n := 0) (i := n)
    (ω := ω))).trans ?_
  simp

omit [∀ n, MeasurableSpace (X n)] in
/-- The stopping rule `S` fires after exactly `n` steps iff the prefix of length `n` belongs to
`S` and no shorter prefix does. -/
lemma hittingAfter_sigmaPrefix_eq_coe_iff :
    hittingAfter (sigmaPrefix Z) S 0 ω = n ↔
      sigmaPrefix Z n ω ∈ S ∧ ∀ j < n, sigmaPrefix Z j ω ∉ S :=
  (hittingAfter_eq_coe_iff (u := sigmaPrefix Z) (s := S) (n := 0) (i := n) (ω := ω)).trans
    (by simp)

omit [∀ n, MeasurableSpace (X n)] in
/-- The prefix stopped at a time equal to `n` is the prefix of length `n`. -/
lemma stoppedValue_sigmaPrefix_of_eq (h : τ ω = n) :
    stoppedValue (sigmaPrefix Z) τ ω = ⟨n, finPrefix Z n ω⟩ := by
  simp only [stoppedValue, h]
  rfl

omit [∀ n, MeasurableSpace (X n)] in
/-- The complement of `{τ ≤ M}` is `{M < τ}`. -/
lemma compl_setOf_le_natCast (τ : Ω → WithTop ℕ) (M : ℕ) :
    {ω | τ ω ≤ M}ᶜ = {ω | (M : WithTop ℕ) < τ ω} := by
  ext ω
  simp

omit [∀ n, MeasurableSpace (X n)] in
/-- The prefix stopped at time `M` has length at most `M`. -/
lemma fst_stoppedProcess_sigmaPrefix_le : (stoppedProcess (sigmaPrefix Z) τ M ω).1 ≤ M := by
  rcases le_or_gt (τ ω) M with h | h
  · rw [stoppedProcess_eq_of_ge (i := M) h]
    exact WithTop.untopA_le h
  · rw [stoppedProcess_eq_of_le (i := M) h.le]
    exact le_rfl

omit [∀ n, MeasurableSpace (X n)] in
/-- The prefix stopped at time `0` is the empty sequence. -/
lemma stoppedProcess_sigmaPrefix_zero (τ : Ω → WithTop ℕ) :
    stoppedProcess (sigmaPrefix Z) τ 0 = fun _ ↦ ⟨0, default⟩ := by
  funext ω
  rw [stoppedProcess_eq_of_le (i := 0) (by simp)]
  exact congrArg (Sigma.mk 0) (Subsingleton.elim _ _)

/-- The prefix stopped at time `0` has the Dirac law at the empty sequence. -/
lemma hasLaw_stoppedProcess_sigmaPrefix_zero (P : Measure Ω) [IsProbabilityMeasure P]
    (τ : Ω → WithTop ℕ) :
    HasLaw (stoppedProcess (sigmaPrefix Z) τ 0)
      (Measure.dirac (⟨0, default⟩ : Σ n : ℕ, Π i : Fin n, X i)) P :=
  hasLaw_dirac_of_ae_eq
    (Filter.Eventually.of_forall (congrFun (stoppedProcess_sigmaPrefix_zero τ)))

end StoppingTime

section Truncation

/-- Truncation of a finite sequence of variable length to its first `M` terms. -/
def truncFin (M : ℕ) (x : Σ n : ℕ, Π i : Fin n, X i) : Σ n : ℕ, Π i : Fin n, X i :=
  if hM : x.1 ≤ M then x else ⟨M, fun i ↦ x.2 (Fin.castLE (not_le.1 hM).le i)⟩

/-- The truncation of finite sequences is measurable. -/
lemma measurable_truncFin (M : ℕ) : Measurable (truncFin (X := X) M) := by
  refine measurable_sigma_of_measurable_comp_mk fun n ↦ ?_
  by_cases hn : n ≤ M
  · simp only [Function.comp_def, truncFin, hn, dite_true]
    exact measurable_sigma_mk n
  · simp only [Function.comp_def, truncFin, hn, dite_false]
    exact (measurable_sigma_mk M).comp
      (Measurable.of_eval fun i ↦ measurable_pi_apply (Fin.castLE (not_le.1 hn).le i))

omit [∀ n, MeasurableSpace (X n)] in
/-- The truncation to the first `M` terms does not change a sequence of length at most `M`. -/
lemma truncFin_of_fst_le {x : Σ n : ℕ, Π i : Fin n, X i} (hM : x.1 ≤ M) : truncFin M x = x :=
  dite_eq_left hM

omit [∀ n, MeasurableSpace (X n)] in
/-- Truncating the prefix stopped at a finite time `τ` to its first `M` terms gives the prefix
stopped at time `M`. -/
lemma truncFin_stoppedValue_sigmaPrefix (h : τ ω ≠ ⊤) :
    truncFin M (stoppedValue (sigmaPrefix Z) τ ω) = stoppedProcess (sigmaPrefix Z) τ M ω := by
  rcases le_or_gt (τ ω) M with hτ | hτ
  · rw [stoppedProcess_eq_of_ge (i := M) hτ]
    exact truncFin_of_fst_le (WithTop.untopA_le hτ)
  · rw [stoppedProcess_eq_of_le (i := M) hτ.le, truncFin, dite_eq_right]
    · rfl
    · exact not_le.2 ((WithTop.lt_untopA_iff h).2 hτ)

omit [∀ n, MeasurableSpace (X n)] in
/-- A truncated sequence has length `< M` iff the original sequence has. -/
lemma preimage_truncFin_fst_lt (M : ℕ) :
    truncFin M ⁻¹' {x : Σ n : ℕ, Π i : Fin n, X i | x.1 < M} = {x | x.1 < M} := by
  ext x
  simp only [Set.mem_preimage, Set.mem_ofPred_eq, truncFin]
  split_ifs with hM
  · rfl
  · simp only [lt_self_iff_false, false_iff, not_lt]
    exact (not_le.1 hM).le

/-- The image of a measure by the truncation to the first `M` terms agrees with the measure on
sequences of length `< M`. -/
lemma restrict_map_truncFin (μ : Measure (Σ n : ℕ, Π i : Fin n, X i)) (M : ℕ) :
    (μ.map (truncFin M)).restrict {x | x.1 < M} = μ.restrict {x | x.1 < M} := by
  rw [Measure.restrict_map (measurable_truncFin M) (measurableSet_sigma_fst_lt M),
    preimage_truncFin_fst_lt]
  conv_rhs => rw [← Measure.map_id (μ := μ.restrict {x | x.1 < M})]
  refine Measure.map_congr ((ae_restrict_iff' (measurableSet_sigma_fst_lt M)).2
    (Filter.Eventually.of_forall fun x hx ↦ ?_))
  exact truncFin_of_fst_le hx.le

omit [∀ n, MeasurableSpace (X n)] in
/-- For an almost surely finite `τ`, the prefix stopped at time `M` is almost surely the
truncation to the first `M` terms of the prefix stopped at `τ`. -/
lemma stoppedProcess_sigmaPrefix_ae_eq_truncFin {P : Measure Ω} (hτ_top : ∀ᵐ ω ∂P, τ ω ≠ ⊤)
    (M : ℕ) :
    stoppedProcess (sigmaPrefix Z) τ M =ᵐ[P] truncFin M ∘ stoppedValue (sigmaPrefix Z) τ := by
  filter_upwards [hτ_top] with ω hω
  exact (truncFin_stoppedValue_sigmaPrefix hω).symm

/-- If the prefix stopped at an almost surely finite `τ` has law `μ`, the prefix stopped at time
`M` has law the image of `μ` by the truncation to the first `M` terms. -/
lemma HasLaw.stoppedProcess_sigmaPrefix {P : Measure Ω} {μ : Measure (Σ n : ℕ, Π i : Fin n, X i)}
    (h : HasLaw (stoppedValue (sigmaPrefix Z) τ) μ P) (hτ_top : ∀ᵐ ω ∂P, τ ω ≠ ⊤) (M : ℕ) :
    HasLaw (stoppedProcess (sigmaPrefix Z) τ M) (μ.map (truncFin M)) P :=
  ((hasLaw_map (measurable_truncFin M).aemeasurable).comp h).congr
    (stoppedProcess_sigmaPrefix_ae_eq_truncFin hτ_top M)

end Truncation

section Measurability

variable (hZ : ∀ n, Measurable (Z n))
include hZ

/-- The prefix of length `n` of a measurable process is measurable. -/
@[fun_prop]
lemma measurable_finPrefix (n : ℕ) : Measurable (finPrefix Z n) :=
  Measurable.of_eval fun i ↦ hZ i

/-- The prefix of length `n`, as a sequence of variable length, is measurable. -/
@[fun_prop]
lemma measurable_sigmaPrefix (n : ℕ) : Measurable (sigmaPrefix Z n) :=
  (measurable_sigma_mk n).comp (measurable_finPrefix hZ n)

end Measurability

/-- The event `{n < τ}`, for the stopping time `τ` of a stopping rule, is determined by the
prefix of length `n`. -/
lemma exists_measurableSet_preimage_lt_hittingAfter_sigmaPrefix (hS : MeasurableSet S) (n : ℕ) :
    ∃ B : Set (Π i : Fin n, X i), MeasurableSet B ∧
      {ω | (n : WithTop ℕ) < hittingAfter (sigmaPrefix Z) S 0 ω} = finPrefix Z n ⁻¹' B := by
  refine ⟨⋂ j, ⋂ (hj : j ≤ n),
    {x | (⟨j, fun i ↦ x (Fin.castLE hj i)⟩ : Σ n, Π i : Fin n, X i) ∉ S}, ?_, ?_⟩
  · refine MeasurableSet.iInter fun j ↦ MeasurableSet.iInter fun hj ↦ ?_
    exact ((measurable_sigma_mk j).comp (Measurable.of_eval fun _ ↦ measurable_pi_apply _))
      hS.compl
  · ext ω
    simp only [Set.mem_ofPred_eq, lt_hittingAfter_sigmaPrefix_iff, Set.mem_preimage,
      Set.mem_iInter]
    exact ⟨fun h j hj ↦ h j hj, fun h j hj ↦ h j hj⟩

section PrefixFiltration

/-- The filtration generated by the prefixes of the process `Z`: `prefixFiltration Z hZ n` is
the σ-algebra generated by the prefix of length `n`, that is by `Z 0, …, Z (n - 1)`, the
information available before step `n`. A stopping time of this filtration decides whether to stop
after `n` steps in terms of the first `n` steps only. -/
def prefixFiltration (Z : (n : ℕ) → Ω → X n) (hZ : ∀ n, Measurable (Z n)) : Filtration ℕ mΩ where
  seq n := MeasurableSpace.comap (finPrefix Z n) inferInstance
  mono' n m hnm := by
    change MeasurableSpace.comap (finPrefix Z n) inferInstance ≤
      MeasurableSpace.comap (finPrefix Z m) inferInstance
    rw [← measurable_iff_comap_le]
    exact measurable_comp_comap (finPrefix Z m)
      (g := fun x : Π i : Fin m, X i ↦ fun i : Fin n ↦ x (Fin.castLE hnm i))
      (Measurable.of_eval fun i ↦ measurable_pi_apply _)
  le' n := (measurable_finPrefix hZ n).comap_le

/-- Unfolding lemma for `prefixFiltration`. -/
lemma prefixFiltration_apply {hZ : ∀ n, Measurable (Z n)} (n : ℕ) :
    prefixFiltration Z hZ n = MeasurableSpace.comap (finPrefix Z n) inferInstance := rfl

/-- A set is measurable for the σ-algebra generated by the prefix of length `n` iff it is the
preimage of a measurable set by that prefix. -/
lemma measurableSet_prefixFiltration_iff {hZ : ∀ n, Measurable (Z n)} {s : Set Ω} :
    MeasurableSet[prefixFiltration Z hZ n] s ↔
      ∃ B : Set (Π i : Fin n, X i), MeasurableSet B ∧ finPrefix Z n ⁻¹' B = s :=
  MeasurableSpace.measurableSet_comap

/-- The prefix of length `n` is measurable for the prefix filtration at time `n`. -/
lemma measurable_finPrefix_prefixFiltration {hZ : ∀ n, Measurable (Z n)} (n : ℕ) :
    Measurable[prefixFiltration Z hZ n] (finPrefix Z n) :=
  measurable_iff_comap_le.2 le_rfl

/-- For a stopping time `τ` of the prefix filtration, the event `{τ ≤ n}` is determined by the
prefix of length `n`. -/
lemma _root_.MeasureTheory.IsStoppingTime.exists_measurableSet_preimage_finPrefix
    {hZ : ∀ n, Measurable (Z n)} (hτ : IsStoppingTime (prefixFiltration Z hZ) τ) (n : ℕ) :
    ∃ B : Set (Π i : Fin n, X i), MeasurableSet B ∧ finPrefix Z n ⁻¹' B = {ω | τ ω ≤ n} :=
  measurableSet_prefixFiltration_iff.1 (hτ.measurableSet_le n)

/-- The stopping time of a stopping rule is a stopping time of the prefix filtration: whether
the process is stopped after `n` steps is determined by the prefix of length `n`. -/
lemma isStoppingTime_hittingAfter_sigmaPrefix (hZ : ∀ n, Measurable (Z n))
    (hS : MeasurableSet S) :
    IsStoppingTime (prefixFiltration Z hZ) (hittingAfter (sigmaPrefix Z) S 0) := by
  intro n
  obtain ⟨B, hB, hB_eq⟩ := exists_measurableSet_preimage_lt_hittingAfter_sigmaPrefix (Z := Z) hS n
  refine measurableSet_prefixFiltration_iff.2 ⟨Bᶜ, hB.compl, ?_⟩
  change finPrefix Z n ⁻¹' Bᶜ = {ω | hittingAfter (sigmaPrefix Z) S 0 ω ≤ (n : WithTop ℕ)}
  rw [Set.preimage_compl, ← hB_eq, ← compl_setOf_le_natCast, compl_compl]

/-- Conversely, every stopping time `τ` of the prefix filtration is the stopping time of a
stopping rule: the rule "stop after `n` steps if the prefix of length `n` belongs to `B n`",
where `{τ ≤ n}` is the preimage of `B n` by the prefix of length `n`. Stopping times of the
prefix filtration and stopping rules are thus two descriptions of the same objects. -/
lemma _root_.MeasureTheory.IsStoppingTime.exists_eq_hittingAfter_sigmaPrefix
    {hZ : ∀ n, Measurable (Z n)} (hτ : IsStoppingTime (prefixFiltration Z hZ) τ) :
    ∃ S : Set (Σ n : ℕ, Π i : Fin n, X i), MeasurableSet S ∧
      τ = hittingAfter (sigmaPrefix Z) S 0 := by
  choose B hB hBτ using hτ.exists_measurableSet_preimage_finPrefix
  refine ⟨{x | x.2 ∈ B x.1}, measurableSet_sigma_iff.2 hB, funext fun ω ↦ ?_⟩
  have hmem : ∀ j : ℕ, sigmaPrefix Z j ω ∈ {x : Σ n : ℕ, Π i : Fin n, X i | x.2 ∈ B x.1} ↔
      τ ω ≤ j := fun j ↦ by
    change ω ∈ finPrefix Z j ⁻¹' B j ↔ _
    rw [hBτ j]
    exact Iff.rfl
  rcases eq_or_ne (τ ω) ⊤ with htop | htop
  · rw [htop, eq_comm, hittingAfter_eq_top_iff]
    intro j _ hj
    have h_le := (hmem j).1 hj
    rw [htop] at h_le
    exact WithTop.natCast_ne_top j (top_le_iff.1 h_le)
  · obtain ⟨k, hk⟩ : ∃ k : ℕ, τ ω = k := by
      obtain ⟨k, hk⟩ := WithTop.ne_top_iff_exists.1 htop
      exact ⟨k, hk.symm⟩
    rw [hk, eq_comm]
    refine hittingAfter_sigmaPrefix_eq_coe_iff.2 ⟨(hmem k).2 hk.le, fun j hj hjS ↦ ?_⟩
    have h_le := (hmem j).1 hjS
    rw [hk] at h_le
    exact absurd (by exact_mod_cast h_le) (not_le.2 hj)

end PrefixFiltration

section Measurability

variable (hZ : ∀ n, Measurable (Z n))
include hZ

/-- The stopping time of a measurable stopping rule is measurable. -/
@[fun_prop]
lemma measurable_hittingAfter_sigmaPrefix (hS : MeasurableSet S) :
    Measurable (hittingAfter (sigmaPrefix Z) S 0) :=
  (isStoppingTime_hittingAfter_sigmaPrefix hZ hS).measurable'

/-- The prefix stopped at a measurable time is measurable. -/
@[fun_prop]
lemma measurable_stoppedValue_sigmaPrefix (hτ : Measurable τ) :
    Measurable (stoppedValue (sigmaPrefix Z) τ) :=
  Measurable.sigmaMk (by fun_prop) (measurable_finPrefix hZ)

/-- The prefix stopped at a measurable time, at time `M`, is measurable. -/
lemma measurable_stoppedProcess_sigmaPrefix (hτ : Measurable τ) (M : ℕ) :
    Measurable (stoppedProcess (sigmaPrefix Z) τ M) :=
  measurable_stoppedValue_sigmaPrefix hZ (by fun_prop)

/-- The prefix stopped by a measurable stopping rule is measurable. -/
lemma measurable_hittingValue_sigmaPrefix (hS : MeasurableSet S) :
    Measurable (hittingValue (sigmaPrefix Z) S 0) :=
  measurable_stoppedValue_sigmaPrefix hZ (measurable_hittingAfter_sigmaPrefix hZ hS)

/-- The prefix stopped by a measurable stopping rule, at time `M`, is measurable. -/
lemma measurable_hittingProcess_sigmaPrefix (hS : MeasurableSet S) (M : ℕ) :
    Measurable (hittingProcess (sigmaPrefix Z) S 0 M) :=
  measurable_stoppedProcess_sigmaPrefix hZ (measurable_hittingAfter_sigmaPrefix hZ hS) M

/-- The event `{τ ≤ M}` for the stopping time of a stopping rule is measurable. -/
lemma measurableSet_hittingAfter_sigmaPrefix_le (hS : MeasurableSet S) (M : ℕ) :
    MeasurableSet {ω | hittingAfter (sigmaPrefix Z) S 0 ω ≤ M} :=
  measurable_hittingAfter_sigmaPrefix hZ hS measurableSet_Iic

/-- The event `{M < τ}` for the stopping time of a stopping rule is measurable. -/
lemma measurableSet_lt_hittingAfter_sigmaPrefix (hS : MeasurableSet S) (M : ℕ) :
    MeasurableSet {ω | (M : WithTop ℕ) < hittingAfter (sigmaPrefix Z) S 0 ω} :=
  measurable_hittingAfter_sigmaPrefix hZ hS measurableSet_Ioi

end Measurability

section ConditionalLaw

variable {β γ : Type*} {mβ : MeasurableSpace β} {mγ : MeasurableSpace γ} {P : Measure Ω}
  [SFinite P]

/-- On the event `{M < τ}`, for a stopping time `τ` of the prefix filtration, which is
determined by the prefix of length `M`, a conditional law given the prefix of length `M` is
preserved. -/
lemma HasCondDistrib.restrict_lt_of_isStoppingTime {Y : Ω → β} {κ : Kernel (Π i : Fin M, X i) β}
    [IsSFiniteKernel κ] {hZ : ∀ n, Measurable (Z n)} (hY : Measurable Y)
    (hτ : IsStoppingTime (prefixFiltration Z hZ) τ) (h : HasCondDistrib Y (finPrefix Z M) κ P) :
    HasCondDistrib Y (finPrefix Z M) κ (P.restrict {ω | (M : WithTop ℕ) < τ ω}) := by
  obtain ⟨B, hB, hBτ⟩ := hτ.exists_measurableSet_preimage_finPrefix M
  rw [← compl_setOf_le_natCast, ← hBτ, ← Set.preimage_compl]
  exact h.restrict_preimage (measurable_finPrefix hZ M) hY hB.compl

/-- On the event `{M < τ}`, for a stopping time `τ` of the prefix filtration, which is
determined by the prefix of length `M`, a conditional law given the prefix of length `M` and
another random variable `W` is preserved. -/
lemma HasCondDistrib.restrict_lt_of_isStoppingTime_prodMk {Y : Ω → β} {W : Ω → γ}
    {κ : Kernel ((Π i : Fin M, X i) × γ) β} [IsSFiniteKernel κ] {hZ : ∀ n, Measurable (Z n)}
    (hY : Measurable Y) (hW : Measurable W) (hτ : IsStoppingTime (prefixFiltration Z hZ) τ)
    (h : HasCondDistrib Y (fun ω ↦ (finPrefix Z M ω, W ω)) κ P) :
    HasCondDistrib Y (fun ω ↦ (finPrefix Z M ω, W ω)) κ
      (P.restrict {ω | (M : WithTop ℕ) < τ ω}) := by
  obtain ⟨B, hB, hBτ⟩ := hτ.exists_measurableSet_preimage_finPrefix M
  have hB' : {ω | (M : WithTop ℕ) < τ ω} =
      (fun ω ↦ (finPrefix Z M ω, W ω)) ⁻¹' (Bᶜ ×ˢ Set.univ) := by
    rw [← compl_setOf_le_natCast, ← hBτ]
    ext ω
    simp
  rw [hB']
  exact h.restrict_preimage ((measurable_finPrefix hZ M).prodMk hW) hY
    (hB.compl.prod MeasurableSet.univ)

/-- On the event `{M < τ}`, for the stopping time `τ` of the stopping rule `S`, which is
determined by the prefix of length `M`, a conditional law given the prefix of length `M` is
preserved. -/
lemma HasCondDistrib.restrict_lt_hittingAfter_sigmaPrefix {Y : Ω → β}
    {κ : Kernel (Π i : Fin M, X i) β}
    [IsSFiniteKernel κ] (hZ : ∀ n, Measurable (Z n)) (hY : Measurable Y) (hS : MeasurableSet S)
    (h : HasCondDistrib Y (finPrefix Z M) κ P) :
    HasCondDistrib Y (finPrefix Z M) κ
      (P.restrict {ω | (M : WithTop ℕ) < hittingAfter (sigmaPrefix Z) S 0 ω}) :=
  h.restrict_lt_of_isStoppingTime hY (isStoppingTime_hittingAfter_sigmaPrefix hZ hS)

/-- On the event `{M < τ}`, for the stopping time `τ` of the stopping rule `S`, which is
determined by the prefix of length `M`, a conditional law given the prefix of length `M` and
another random variable `W` is preserved. -/
lemma HasCondDistrib.restrict_lt_hittingAfter_sigmaPrefix_prodMk {Y : Ω → β} {W : Ω → γ}
    {κ : Kernel ((Π i : Fin M, X i) × γ) β} [IsSFiniteKernel κ] (hZ : ∀ n, Measurable (Z n))
    (hY : Measurable Y) (hW : Measurable W) (hS : MeasurableSet S)
    (h : HasCondDistrib Y (fun ω ↦ (finPrefix Z M ω, W ω)) κ P) :
    HasCondDistrib Y (fun ω ↦ (finPrefix Z M ω, W ω)) κ
      (P.restrict {ω | (M : WithTop ℕ) < hittingAfter (sigmaPrefix Z) S 0 ω}) :=
  h.restrict_lt_of_isStoppingTime_prodMk hY hW (isStoppingTime_hittingAfter_sigmaPrefix hZ hS)

/-- If `Z n` has conditional law `κ` given the prefix of length `n` under a measure `Q`, then the
law of the prefix of length `n + 1` under `Q` is the composition-product of the law of the prefix
of length `n` with `κ`. -/
lemma map_finPrefix_succ_of_hasCondDistrib {Q : Measure Ω} {κ : Kernel (Π i : Fin n, X i) (X n)}
    (hZ : ∀ n, Measurable (Z n)) (h : HasCondDistrib (Z n) (finPrefix Z n) κ Q) :
    Q.map (finPrefix Z (n + 1)) =
      (Q.map (finPrefix Z n) ⊗ₘ κ).map (MeasurableEquiv.piFinSuccProd X n).symm := by
  rw [finPrefix_succ, ← h.map_eq,
    Measure.map_map (MeasurableEquiv.piFinSuccProd X n).symm.measurable (by fun_prop)]

end ConditionalLaw

section Law

variable (hZ : ∀ n, Measurable (Z n)) {P : Measure Ω}
include hZ

/-- The law of the prefix stopped at time `M` splits according to whether `τ ≤ M`: on `{τ ≤ M}`
it is the law of the prefix stopped at `τ`, on `{M < τ}` it is the law of the prefix of
length `M`. -/
lemma map_stoppedProcess_sigmaPrefix_eq_add (hτ : Measurable τ) (M : ℕ) :
    P.map (stoppedProcess (sigmaPrefix Z) τ M) =
      (P.restrict {ω | τ ω ≤ M}).map (stoppedProcess (sigmaPrefix Z) τ M) +
        ((P.restrict {ω | (M : WithTop ℕ) < τ ω}).map (finPrefix Z M)).map (Sigma.mk M) := by
  have hm := measurable_stoppedProcess_sigmaPrefix hZ hτ M
  have hle : MeasurableSet {ω | τ ω ≤ M} := hτ measurableSet_Iic
  conv_lhs => rw [← Measure.restrict_add_restrict_compl (μ := P) hle, Measure.map_add _ _ hm,
    compl_setOf_le_natCast]
  congr 1
  rw [Measure.map_map (measurable_sigma_mk M) (measurable_finPrefix hZ M)]
  refine Measure.map_congr ((ae_restrict_iff' (hle.compl.congr ?_)).2
    (Filter.Eventually.of_forall fun ω hω ↦ ?_))
  · exact compl_setOf_le_natCast τ M
  · exact stoppedProcess_eq_of_le (i := M) hω.le

/-- The law of the prefix stopped at time `M + 1` splits according to whether `τ ≤ M`: on
`{τ ≤ M}` it is the law of the prefix stopped at time `M`, on `{M < τ}` it is the law of the
prefix of length `M + 1`. -/
lemma map_stoppedProcess_sigmaPrefix_succ_eq_add (hτ : Measurable τ) (M : ℕ) :
    P.map (stoppedProcess (sigmaPrefix Z) τ (M + 1)) =
      (P.restrict {ω | τ ω ≤ M}).map (stoppedProcess (sigmaPrefix Z) τ M) +
        ((P.restrict {ω | (M : WithTop ℕ) < τ ω}).map (finPrefix Z (M + 1))).map
          (Sigma.mk (M + 1)) := by
  have hm := measurable_stoppedProcess_sigmaPrefix hZ hτ (M + 1)
  have hle : MeasurableSet {ω | τ ω ≤ M} := hτ measurableSet_Iic
  conv_lhs => rw [← Measure.restrict_add_restrict_compl (μ := P) hle, Measure.map_add _ _ hm,
    compl_setOf_le_natCast]
  congr 1
  · refine Measure.map_congr ((ae_restrict_iff' hle).2
      (Filter.Eventually.of_forall fun ω hω ↦ ?_))
    rw [stoppedProcess_eq_of_ge (i := M) hω,
      stoppedProcess_eq_of_ge (i := M + 1) (hω.trans (WithTop.coe_le_coe.2 (Nat.le_add_right M 1)))]
  · rw [Measure.map_map (measurable_sigma_mk (M + 1)) (measurable_finPrefix hZ (M + 1))]
    refine Measure.map_congr ((ae_restrict_iff' (hle.compl.congr (compl_setOf_le_natCast τ M))).2
      (Filter.Eventually.of_forall fun ω hω ↦ ?_))
    refine stoppedProcess_eq_of_le (i := M + 1) ?_
    push_cast
    exact Order.add_one_le_of_lt (α := ℕ∞) (show (M : WithTop ℕ) < τ ω from hω)

omit hZ in
/-- The image of the restriction of `P` to `A` by `f` gives measure zero to a set avoided by `f`
on `A`. -/
lemma _root_.MeasureTheory.Measure.map_restrict_apply_of_forall_notMem {H : Type*}
    {mH : MeasurableSpace H} {f : Ω → H} (hf : Measurable f) {A : Set Ω} {T : Set H}
    (hT : MeasurableSet T) (h : ∀ ω ∈ A, f ω ∉ T) : ((P.restrict A).map f) T = 0 := by
  rw [Measure.map_apply hf hT, Measure.restrict_apply (hf hT)]
  exact measure_mono_null (fun ω hω ↦ (h ω hω.2 hω.1).elim) measure_empty

/-- The prefix stopped at time `M` has length at most `M`. -/
lemma map_restrict_stoppedProcess_sigmaPrefix_apply_compl_fst_le (hτ : Measurable τ) (A : Set Ω)
    (M : ℕ) :
    ((P.restrict A).map (stoppedProcess (sigmaPrefix Z) τ M)) {x | x.1 ≤ M}ᶜ = 0 :=
  Measure.map_restrict_apply_of_forall_notMem (measurable_stoppedProcess_sigmaPrefix hZ hτ M)
    (measurableSet_sigma_fst_le M).compl fun _ _ h ↦ h fst_stoppedProcess_sigmaPrefix_le

/-- On `{τ ≤ M}`, for a time `τ` such that `{τ ≤ M}` is the preimage of `B` by the prefix of
length `M`, the prefix stopped at time `M` has length less than `M` or is a prefix of length `M`
in `B`. -/
lemma map_restrict_le_stoppedProcess_sigmaPrefix_apply_compl (hτ : Measurable τ)
    {B : Set (Π i : Fin M, X i)} (hB : MeasurableSet B)
    (hBτ : finPrefix Z M ⁻¹' B = {ω | τ ω ≤ M}) :
    ((P.restrict {ω | τ ω ≤ M}).map (stoppedProcess (sigmaPrefix Z) τ M))
      ({x : Σ n : ℕ, Π i : Fin n, X i | x.1 < M} ∪ Sigma.mk M '' B)ᶜ = 0 := by
  refine Measure.map_restrict_apply_of_forall_notMem (measurable_stoppedProcess_sigmaPrefix hZ hτ M)
    ((measurableSet_sigma_fst_lt M).union
      ((measurableEmbedding_sigma_mk M).measurableSet_image.2 hB)).compl fun ω hω h ↦ h ?_
  have hτω : τ ω ≠ ⊤ := ne_top_of_le_ne_top (WithTop.natCast_ne_top M) hω
  obtain ⟨k, hk⟩ : ∃ k : ℕ, τ ω = k := by
    obtain ⟨k, hk⟩ := WithTop.ne_top_iff_exists.1 hτω
    exact ⟨k, hk.symm⟩
  have hkM : k ≤ M := by
    have h_le : τ ω ≤ M := hω
    rw [hk] at h_le
    exact_mod_cast h_le
  rw [stoppedProcess_eq_of_ge (i := M) hω]
  change stoppedValue (sigmaPrefix Z) τ ω ∈ _
  rw [stoppedValue_sigmaPrefix_of_eq hk]
  rcases hkM.lt_or_eq with hlt | rfl
  · exact Or.inl hlt
  · refine Or.inr ⟨finPrefix Z k ω, ?_, rfl⟩
    rw [← Set.mem_preimage, hBτ]
    exact hω

/-- On `{M < τ}`, for a time `τ` such that `{τ ≤ M}` is the preimage of `B` by the prefix of
length `M`, the prefix of length `M` does not belong to `B`. -/
lemma map_restrict_lt_map_finPrefix_map_sigmaMk_apply {B : Set (Π i : Fin M, X i)}
    (hB : MeasurableSet B) (hBτ : finPrefix Z M ⁻¹' B = {ω | τ ω ≤ M}) :
    (((P.restrict {ω | (M : WithTop ℕ) < τ ω}).map (finPrefix Z M)).map (Sigma.mk M))
      ({x : Σ n : ℕ, Π i : Fin n, X i | x.1 < M} ∪ Sigma.mk M '' B) = 0 := by
  rw [Measure.map_map (measurable_sigma_mk M) (measurable_finPrefix hZ M)]
  refine Measure.map_restrict_apply_of_forall_notMem
    ((measurable_sigma_mk M).comp (measurable_finPrefix hZ M))
    ((measurableSet_sigma_fst_lt M).union
      ((measurableEmbedding_sigma_mk M).measurableSet_image.2 hB)) fun ω hω h ↦ ?_
  simp only [Function.comp_apply, Set.mem_union, Set.mem_ofPred_eq, lt_self_iff_false,
    sigma_mk_injective.mem_set_image, false_or] at h
  rw [← Set.mem_preimage, hBτ] at h
  exact not_le.2 (show (M : WithTop ℕ) < τ ω from hω) (show τ ω ≤ M from h)

end Law

end ProbabilityTheory
